Repository XPEHO/YAKI, pull requests merged in 2023-05, with the labels that each got.

#306 Test/team karate
  yaki_karate/src/test/resources/teamAdmin.feature
Labels: 🚧 Technical stuff, other

#323 feat(admin-layout): set modular page layout
  yaki_admin/.gitignore
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/App.vue
  yaki_admin/src/assets/.gitkeep
  yaki_admin/src/assets/style.css
  yaki_admin/src/assets/style.scss
  yaki_admin/src/features/captain/components/.gitkeep
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListing.vue
  yaki_admin/src/features/captain/layouts/.gitkeep
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
  yaki_admin/src/features/captain/pages/.gitkeep
  yaki_admin/src/features/captain/pages/PageCaptain.vue
  yaki_admin/src/main.ts
  yaki_admin/src/router/index.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/shared/components/.gitkeep
  yaki_admin/src/shared/components/AddTeamButton.vue
  yaki_admin/src/shared/components/HeaderYaki.vue
  yaki_admin/src/shared/components/SideBar.vue
  yaki_admin/src/shared/layouts/.gitkeep
  yaki_admin/src/shared/layouts/PageLayout.vue
Labels: enhancement :rocket:

#330 Feat/admin captain teammate view
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/assets/Delete.png
  yaki_admin/src/assets/Edit.png
  yaki_admin/src/assets/avatar.png
  yaki_admin/src/features/captain/components/teamMate.vue
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/team.type.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/src/services/teamMate.type.ts
  yaki_admin/src/services/user.type.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeammateDetailsEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeammateService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateControllerTests.java
  yaki_karate/src/test/resources/teamAdmin.feature
Labels: enhancement :rocket:

#332 Feat/front admin styling
  yaki_admin/.gitignore
  yaki_admin/package-lock.json
  yaki_admin/src/App.vue
  yaki_admin/src/assets/LOGO 512.png
  yaki_admin/src/assets/LOGO.png
  yaki_admin/src/assets/Vector.png
  yaki_admin/src/assets/account-group-outline.png
  yaki_admin/src/assets/plus.png
  yaki_admin/src/assets/power.png
  yaki_admin/src/assets/security.png
  yaki_admin/src/assets/style.css
  yaki_admin/src/assets/style.scss
  yaki_admin/src/assets/style/style.css
  yaki_admin/src/assets/style/style.scss
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListElement.vue
  yaki_admin/src/features/captain/components/TeamListing.vue
  yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
  yaki_admin/src/features/captain/pages/PageCaptain.vue
  yaki_admin/src/features/captain/services/.gitkeep
  yaki_admin/src/features/captain/services/isActiveTeam.ts
  yaki_admin/src/main.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/shared/components/AddTeamButton.vue
  yaki_admin/src/shared/components/HeaderYaki.vue
  yaki_admin/src/shared/components/SideBar.vue
  yaki_admin/src/shared/components/SideBarButton.vue
  yaki_admin/src/shared/components/SideBarElement.vue
  yaki_admin/src/shared/layouts/PageLayout.vue
Labels: enhancement :rocket:

#333 Fix/declaration page responsiveness
  yaki_mobile/lib/presentation/styles/header_text_style.dart
  yaki_mobile/lib/presentation/ui/declaration/afternoon_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/morning_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/afternoon_declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/morning_declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/status_card.dart
  yaki_mobile/lib/presentation/ui/shared/pages_layout_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/status/halfday_status.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
Labels: bug :bug:

#337 Feature/front admin captain
  yaki_admin/.gitignore
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/App.vue
  yaki_admin/src/assets/.gitkeep
  yaki_admin/src/assets/Delete.png
  yaki_admin/src/assets/Edit.png
  yaki_admin/src/assets/LOGO 512.png
  yaki_admin/src/assets/LOGO.png
  yaki_admin/src/assets/Vector.png
  yaki_admin/src/assets/account-group-outline.png
  yaki_admin/src/assets/avatar.png
  yaki_admin/src/assets/plus.png
  yaki_admin/src/assets/power.png
  yaki_admin/src/assets/security.png
  yaki_admin/src/assets/style/style.css
  yaki_admin/src/assets/style/style.scss
  yaki_admin/src/features/captain/components/.gitkeep
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListElement.vue
  yaki_admin/src/features/captain/components/teamMate.vue
  yaki_admin/src/features/captain/layouts/.gitkeep
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/features/captain/pages/.gitkeep
  yaki_admin/src/features/captain/pages/PageCaptain.vue
  yaki_admin/src/features/captain/services/.gitkeep
  yaki_admin/src/features/captain/services/isActiveTeam.ts
  yaki_admin/src/main.ts
  yaki_admin/src/router/index.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/team.type.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/src/services/teamMate.type.ts
  yaki_admin/src/services/user.type.ts
  yaki_admin/src/shared/components/.gitkeep
  yaki_admin/src/shared/components/HeaderYaki.vue
  yaki_admin/src/shared/components/SideBar.vue
  yaki_admin/src/shared/components/SideBarButton.vue
  yaki_admin/src/shared/components/SideBarElement.vue
  yaki_admin/src/shared/layouts/.gitkeep
  yaki_admin/src/shared/layouts/PageLayout.vue
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeammateDetailsEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeammateService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateControllerTests.java
Labels: enhancement :rocket:

#366 chore(migration): upgrade to flutter 3.10
  .github/workflows/test_&_build.yaml
  yaki_mobile/analysis_options.yaml
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.g.dart
  yaki_mobile/lib/data/sources/remote/login_api.g.dart
  yaki_mobile/lib/data/sources/remote/team_api.g.dart
  yaki_mobile/lib/data/sources/remote/team_mate_api.g.dart
  yaki_mobile/lib/presentation/ui/authentication/logger.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.look.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/goldens/Header.png
Labels: chore :construction_worker_man:

#335 chore(sonar): configure sonar scan for admin backend
  .github/workflows/sonar.yaml
  yaki_admin_backend/build.gradle
Labels: chore :construction_worker_man:

#369 chore(dependabot_update): change the dependabot updates frequency to …
  .github/dependabot.yml
Labels: chore :construction_worker_man:

#373 chore(sonar): add jacoco plugin for test coverage
  yaki_admin_backend/build.gradle
Labels: chore :construction_worker_man:

#345 Feature/front admin login
  yaki_admin/src/assets/banner2.png
  yaki_admin/src/assets/eye.png
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/features/login/layouts/PageLoginLayout.vue
  yaki_admin/src/features/login/pages/PageLogin.vue
  yaki_admin/src/router/router.ts
Labels: enhancement :rocket:, 🚧 Technical stuff, 🖥 Desktop

#379 Fix/front admin
  yaki_admin/src/features/login/pages/PageLogin.vue
  yaki_admin/src/router/router.ts
Labels: bug :bug:, 🖥 Desktop

#390 chore(SetupPinia): install pinia and create the first store
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/main.ts
  yaki_admin/src/stores/teamStore.js
Labels: chore :construction_worker_man:

#377 docs(admin_backend_doc_readme): create documentation for use backend …
  CONTRIBUTING.md
  README.md
  yaki_admin/CONTRIBUTING.md
  yaki_admin/README.md
  yaki_admin_backend/CONTRIBUTING.md
  yaki_admin_backend/README.md
  yaki_admin_backend/src/main/resources/application.properties.sample
  yaki_backend/CONTRIBUTING.md
  yaki_backend/README.md
  yaki_database/CONTRIBUTING.md
  yaki_database/README.md
  yaki_docker/.env.sample
  yaki_docker/CONTRIBUTING.md
  yaki_docker/README.md
  yaki_karate/CONTRIBUTING.md
  yaki_karate/README.md
  yaki_mobile/CONTRIBUTING.md
  yaki_mobile/README.md
Labels: other

#391 Feat/selesct team admin
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListElement.vue
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/features/captain/services/isActiveTeam.ts
  yaki_admin/src/main.ts
  yaki_admin/src/stores/teamStore.js
Labels: enhancement :rocket:, 🖥 Desktop

#402 chore(publish_docker_mobile): add the new job
  .github/workflows/docker push.yaml
Labels: chore :construction_worker_man:

#403 chore(back_admin_docker_image): add jobs to create docker image of ba…
  .github/workflows/docker push.yaml
  yaki_admin_backend/build.gradle
Labels: chore :construction_worker_man:

#404 chore(uat): add restart uat workflow
  .github/workflows/restart_uat.yaml
  .gitignore
Labels: chore :construction_worker_man:

#405 chore(published_docker_front_admin): create docker image and ci for f…
  .github/workflows/docker push.yaml
  yaki_admin/dockerfile
Labels: chore :construction_worker_man:

#406 Fix/sonarqube security
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateControllerTests.java
  yaki_backend/src/features/captain/captain.repository.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/teamMate/teamMate.repository.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/server.ts
Labels: bug :bug:

#414 Fix/code smell sonarqube
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/YakiAdminBackendApplicationTests.java
Labels: bug :bug:
