Repository XPEHO/YAKI, pull requests merged in 2023-08, with the labels that each got.

#654 Fix/mobile registration
  PRIVACY_POLICY.md
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/ui/registration/registration.dart
  yaki_mobile/lib/presentation/ui/registration/view/registration_snackbar.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_registration_page.dart
Labels: bug :bug:

#672 Feat/page customer
  yaki_admin/src/assets/style/style.css
  yaki_admin/src/envPlaceholder.ts
  yaki_admin/src/features/customer/components/CaptainElement.vue
  yaki_admin/src/features/customer/components/SideBarCustomer.vue
  yaki_admin/src/features/customer/layouts/LayoutCaptainByCustomer.vue
  yaki_admin/src/features/customer/layouts/LayoutCustomer.vue
  yaki_admin/src/features/customer/layouts/LayoutTeamByCustomer.vue
  yaki_admin/src/features/shared/components/SideBar.vue
  yaki_admin/src/features/shared/components/SideBarElement.vue
  yaki_admin/src/models/captain.type.ts
  yaki_admin/src/models/customer.type.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/captain.service.ts
  yaki_admin/src/services/customer.service.ts
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/stores/authStore.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/customerRightsStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CaptainService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/AuthenticationController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
Labels: enhancement :rocket:

#673 chore(flutter_version): increase version
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#648 Fix/handle log table
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CaptainModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/EntityLogModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeammateModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/EntityLogServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/EntityLogJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
Labels: bug :bug:

#690 fix(mobile_api): fix and change api to match the updated database
  yaki_backend/src/__test__/__mocks__/captain.ts
  yaki_backend/src/__test__/__mocks__/mockDbUsers.ts
  yaki_backend/src/__test__/__mocks__/team.ts
  yaki_backend/src/__test__/__mocks__/teamMate.ts
  yaki_backend/src/__test__/__mocks__/teamMateWithDeclaration.ts
  yaki_backend/src/__test__/captain-service.test.ts
  yaki_backend/src/__test__/team-service.test.ts
  yaki_backend/src/__test__/teamMates.test.ts
  yaki_backend/src/__test__/teammate.test.ts
  yaki_backend/src/__test__/user-service.test.ts
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/create_user.ts
  yaki_backend/src/db/initdb.ts
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/declaration.router.ts
  yaki_backend/src/features/captain/captain.controller.ts
  yaki_backend/src/features/captain/captain.dtoIn.ts
  yaki_backend/src/features/captain/captain.repository.ts
  yaki_backend/src/features/captain/captain.service.ts
  yaki_backend/src/features/declaration/declaration.dtoIn.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/team/team.dtoIn.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/team/team.service.ts
  yaki_backend/src/features/teamMate/teamMate.dtoOut.ts
  yaki_backend/src/features/teamMate/teamMate.service.ts
  yaki_backend/src/features/teamMate/teamMateWithDeclaration.dtoOut.ts
  yaki_backend/src/features/teammate/teammate.controller.ts
  yaki_backend/src/features/teammate/teammate.dtoIn.ts
  yaki_backend/src/features/teammate/teammate.dtoOut.ts
  yaki_backend/src/features/teammate/teammate.repository.ts
  yaki_backend/src/features/teammate/teammate.service.ts
  yaki_backend/src/features/teammate/teammateWithDeclaration.dtoOut.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/toRegister.dtoIn.ts
  yaki_backend/src/features/user/toRegister.dtoOut.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_backend/src/server.ts
Labels: bug :bug:

#702 fix(mobile_popup): not display popup when only one team
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/halfday_status_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/providers/halfday_status_provider.dart
  yaki_mobile/lib/presentation/state/providers/status_provider.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/declaration/afternoon_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/morning_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/afternoon_declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/morning_declaration_body.dart
  yaki_mobile/lib/presentation/ui/shared/views/team_selection_dialog.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_fullday.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_halfday.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
Labels: bug :bug:

#707 Feature/holiday declaration
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/domain/entities/delcaration_entity_in.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/vacation_status_notifier.dart
  yaki_mobile/lib/presentation/state/providers/vacation_status_provider.dart
  yaki_mobile/lib/presentation/state/state/state_vacation_page.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/status/vacation_status.dart
  yaki_mobile/lib/presentation/ui/vacation/vacation_selection_dialog.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
Labels: enhancement :rocket:

#698 fix(captain_invite): change fetch range
  yaki_admin/src/envPlaceholder.ts
  yaki_mobile/assets/translations/en.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/ui/captain/views/teammate_card.dart
  yaki_mobile/lib/presentation/ui/captain/views/teammate_card_halfday.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/test/unit/data/models/login_model_test.dart
  yaki_mobile/test/unit/data/models/user_test.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.dart
  yaki_mobile/test/unit/data/repositories/teammate_repository_test.dart
Labels: bug :bug:

#709 fix(mobile): new flutter version
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#716 fix(mobile_validation_register)
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
Labels: bug :bug:, security 🚨

#721 Chore/refacto pinia store
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/customer/layouts/LayoutCaptainByCustomer.vue
  yaki_admin/src/features/customer/layouts/LayoutTeamByCustomer.vue
  yaki_admin/src/features/invitation/components/UserInvitationCard.vue
  yaki_admin/src/models/authenticate.type.ts
  yaki_admin/src/services/captain.service.ts
  yaki_admin/src/stores/authStore.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/customerRightsStore.ts
  yaki_admin/src/stores/roleStore.ts
  yaki_admin/src/stores/selectedRole.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/AuthenticationResponseEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CaptainService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
Labels: chore :construction_worker_man:

#723 Fix/vue3 archi change
  yaki_admin/src/assets/sound/btnClick.mp3
  yaki_admin/src/assets/style/_batiUI-btn.scss
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/assets/style/_variables.scss
  yaki_admin/src/assets/style/main.css
  yaki_admin/src/assets/style/main.css.map
  yaki_admin/src/envPlaceholder.ts
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/captain/services/teamList.ts
  yaki_admin/src/features/customer/components/SideBarCustomer.vue
  yaki_admin/src/features/customer/layouts/CustomerPageContentCaptainList.vue
  yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue
  yaki_admin/src/features/customer/layouts/LayoutCaptainByCustomer.vue
  yaki_admin/src/features/customer/layouts/LayoutTeamByCustomer.vue
  yaki_admin/src/features/invitation/components/InvitationCard.vue
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/features/invitation/services/userService.ts
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/features/shared/components/DefaultButton.vue
  yaki_admin/src/features/shared/components/HeaderContentPage.vue
  yaki_admin/src/features/shared/components/SideBarTeamsListElement.vue
  yaki_admin/src/features/shared/components/UserCard.vue
  yaki_admin/src/features/shared/popup/ModalFrame.vue
  yaki_admin/src/features/shared/popup/ModalTeam.vue
  yaki_admin/src/features/shared/popup/ModalValidation.vue
  yaki_admin/src/features/shared/popup/layouts/ModalContentDeletionValidation.vue
  yaki_admin/src/features/shared/popup/layouts/ModalContentTeams.vue
  yaki_admin/src/features/shared/services/isSelectedTeamActive.ts
  yaki_admin/src/features/shared/services/modalMode.ts
  yaki_admin/src/features/shared/services/modalState.ts
  yaki_admin/src/features/shared/services/modalTeamState.ts
  yaki_admin/src/features/shared/services/modalValidationState.ts
  yaki_admin/src/global-layouts/PageLayout.vue
  yaki_admin/src/global-layouts/SideBar.vue
  yaki_admin/src/models/teammate.type.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/teammate.service.ts
  yaki_admin/src/stores/authStore.ts
  yaki_admin/src/stores/roleStore.ts
  yaki_admin/src/stores/selectedRole.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin/test/features/captain/services/isActiveTeam.test.js
Labels: bug :bug:

#725 fix(admin_back_get_admins): create a new route to get all admin userId
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CustomerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
Labels: bug :bug:, backend-admin

#726 Feat/front customer rights
  yaki_admin/src/features/customer/components/SideBarCustomer.vue
  yaki_admin/src/features/invitation/components/InvitationCard.vue
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/features/invitation/services/invitationService.ts
  yaki_admin/src/features/invitation/services/userService.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/captain.service.ts
  yaki_admin/src/services/customer.service.ts
  yaki_admin/src/stores/selectedRole.ts
Labels: enhancement :rocket:, 🖥 Desktop

#729 Feat/delete user
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplTest.java
Labels: enhancement :rocket:, backend-admin
