Repository XPEHO/YAKI, pull requests merged in 2023-06, with the labels that each got.

#415 fix(bug_yaki_admin_backend_sonarqube): fix bug
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
Labels: bug :bug:

#413 fix(security_back_admin): add configurations for cors
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configuration/WebSecurityConfig.java
Labels: bug :bug:

#435 Test/coverage admin back
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplTest.java
  yaki_mobile/Dockerfile
Labels: enhancement :rocket:, other, 🖥 Desktop

#437 chore(back_security_sql): remove the injection sql reported by sonarqube
  yaki_backend/src/features/declaration/declaration.repository.ts
Labels: bug :bug:, chore :construction_worker_man:

#439 fix(add-baseref): added a base-ref option to flutter build web command
  .github/workflows/docker push.yaml
Labels: bug :bug:

#440 fix(front_build):Fix incorrect front end build, add .env, workflow
  .github/workflows/docker push.yaml
  yaki_admin/README.md
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/assets/style/style.css
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/src/stores/teamStore.js
  yaki_admin/tsconfig.json
  yaki_admin/tsconfig.node.json
  yaki_admin/vite.config.ts
Labels: bug :bug:

#442 Fix/cross origin admin docker
  yaki_admin/dockerfile
  yaki_admin_backend/README.md
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/YakiAdminBackendApplication.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configuration/WebSecurityConfig.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
Labels: bug :bug:

#443 fix(build-web): added env on flutter build web command
  .github/workflows/docker push.yaml
Labels: bug :bug:

#444 fix(build-web): added base href
  .github/workflows/docker push.yaml
Labels: bug :bug:

#445 feat(admin_user_crud): add save
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeammateEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntityIn.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Labels: enhancement :rocket:

#446 Fix/flutter web deploy
  .github/workflows/docker push.yaml
Labels: bug :bug:

#455 chore(sonarqube): add admin to scan
  .github/workflows/sonar.yaml
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/sonar-project.properties
  yaki_admin/test/features/captain/services/isActiveTeam.test.js
  yaki_admin/tsconfig.json
  yaki_admin/tsconfig.node.json
  yaki_admin/vite.config.ts
  yaki_admin/vitest.config.ts
Labels: chore :construction_worker_man:

#460 fix(flutter-web): added api base url
  .github/workflows/docker push.yaml
Labels: bug :bug:

#461 Fix/GitHub image front admin
  .github/workflows/docker push.yaml
  yaki_admin/dockerfile
  yaki_admin/package-lock.json
  yaki_admin/package.json
Labels: bug :bug:

#464 fix(lint_admin_front): fix error coming from lint check
  yaki_admin/package.json
  yaki_admin/src/App.vue
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListElement.vue
  yaki_admin/src/features/captain/layouts/ContentCaptain.vue
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/test/features/captain/services/isActiveTeam.test.js
Labels: bug :bug:

#438 chore(sonarqube): add files thats should not be tracked by sonarqube
  yaki_backend/sonar-project.properties
Labels: chore :construction_worker_man:

#467 Fix/deploy web
  yaki_mobile/lib/presentation/state/dio/custom_adapter.dart
  yaki_mobile/lib/presentation/state/dio/dio_interceptor.dart
  yaki_mobile/lib/presentation/state/dio/mobile_oriented_adapter.dart
  yaki_mobile/lib/presentation/state/dio/web_oriented_adapter.dart
Labels: bug :bug:

#441 chore(upload_bundle): create upload bundle workflow
  .github/workflows/upload_appbundle.yaml
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#470 Fix/workflow chain
  .github/workflows/restart_uat.yaml
Labels: bug :bug:

#477 Fix/admin front end env at runtime
  yaki_admin/dockerfile
  yaki_admin/nginx.conf
  yaki_admin/package.json
  yaki_admin/src/envPlaceholder.ts
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/substitute_environment_variables.sh
Labels: bug :bug:

#476 Feat/flutter refresh
  yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
  yaki_mobile/lib/presentation/ui/shared/pages_layout.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
Labels: enhancement :rocket:

#468 Fix/admin back docker envar
  .github/workflows/docker push.yaml
  yaki_admin/dockerfile
Labels: bug :bug:

#481 Feat/authentication failed notice
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/presentation/displaydata/status_page_content.dart
  yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
Labels: enhancement :rocket:

#491 fix(yaki-icon): added yaki icons for android, ios and web browser
  yaki_mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  yaki_mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  yaki_mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  yaki_mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  yaki_mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  yaki_mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  yaki_mobile/pubspec.yaml
  yaki_mobile/web/favicon.png
  yaki_mobile/web/icons/Icon-192.png
  yaki_mobile/web/icons/Icon-512.png
  yaki_mobile/web/icons/Icon-maskable-192.png
  yaki_mobile/web/icons/Icon-maskable-512.png
  yaki_mobile/web/manifest.json
Labels: bug :bug:

#492 feat(show-password): add button to show plain text password
  yaki_mobile/lib/presentation/ui/shared/views/input_app.dart
Labels: enhancement :rocket:

#483 Feat/password encryption back
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/YakiAdminBackendApplication.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/ApplicationConfig.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/__test__/__mocks__/user.ts
  yaki_backend/src/__test__/authenticate-service.test.ts
  yaki_backend/src/__test__/user-service.test.ts
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_karate/src/test/resources/authenticate.feature
  yaki_karate/src/test/resources/login.feature
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/.test_optimizer.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.mocks.dart
Labels: enhancement :rocket:

#480 Chore/delete back mobile test data script
  yaki_backend/src/db/starting_data.sql
  yaki_karate/CONTRIBUTING.md
  yaki_karate/src/test/resources/adminCaptain.feature
  yaki_karate/src/test/resources/adminCustomer.feature
  yaki_karate/src/test/resources/adminOwner.feature
  yaki_karate/src/test/resources/adminTeam.feature
  yaki_karate/src/test/resources/authenticate.feature
  yaki_karate/src/test/resources/captain.feature
  yaki_karate/src/test/resources/captainAdmin.feature
  yaki_karate/src/test/resources/captainGetTeamate.feature
  yaki_karate/src/test/resources/creationDeclaration.feature
  yaki_karate/src/test/resources/declaration.feature
  yaki_karate/src/test/resources/getCaptain.feature
  yaki_karate/src/test/resources/getLatestDeclaration.feature
  yaki_karate/src/test/resources/getTeamMates.feature
  yaki_karate/src/test/resources/login.feature
  yaki_karate/src/test/resources/ownerAdmin.feature
  yaki_karate/src/test/resources/teamAdmin.feature
Labels: chore :construction_worker_man:

#497 Feat/remember me
  .github/workflows/karate.yaml
  yaki_karate/src/test/resources/adminCaptain.feature
  yaki_karate/src/test/resources/adminOwner.feature
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/sources/local/shared_preference.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/shared/views/custom_checkbox.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_app.dart
Labels: enhancement :rocket:

#499 chore(modificationCI): add application-test-properties for run in CI
  .github/workflows/test_&_build.yaml
Labels: chore :construction_worker_man:

#501 Chore/modification ci
  .github/workflows/test_&_build.yaml
  yaki_admin_backend/README.md
Labels: chore :construction_worker_man:

#502 feat(captain_view_query): change captain view sql query
  yaki_backend/src/features/teamMate/teamMate.repository.ts
Labels: enhancement :rocket:

#504 feat(admin-front-tab): add favicon & tab name
  yaki_admin/index.html
  yaki_admin/public/favicon.png
  yaki_admin/vite.config.ts
Labels: enhancement :rocket:

#505 chore(codeql): configure Github codeql scan
  .github/workflows/codeql.yml
Labels: chore :construction_worker_man:

#509 feat(mobile_captain_query): sql query change for mobile captain view
  yaki_admin/vite.config.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/teamMate/teamMate.repository.ts
Labels: enhancement :rocket:

#503 Feat/temporary profile page
  yaki_mobile/assets/images/exit.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/state/notifiers/halfday_status_notifier.dart
  yaki_mobile/lib/presentation/ui/captain/captain_view.dart
  yaki_mobile/lib/presentation/ui/profile/profile.dart
  yaki_mobile/lib/presentation/ui/shared/views/custom_checkbox.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_with_label_app.dart
  yaki_mobile/lib/presentation/ui/status/halfday_status.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
Labels: enhancement :rocket:
