Repository XPEHO/YAKI, pull requests merged in 2023-04, with the labels that each got.

#188 feature(admin_db): create table owner and customer
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/starting_data.sql
  yaki_database/create_tables.sql
  yaki_karate/src/test/resources/getCaptain.feature
Labels: enhancement :rocket:

#187 fix(SwaggerForCI): add cmd line to generate swagger for the CI
  .github/workflows/karate.yaml
  yaki_backend/src/dev/swagger.json
Labels: bug :bug:

#173 fix(UnableToUseSwagger): add body and header in swagger
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/router.ts
Labels: bug :bug:

#197 Fix/encrypt password
  yaki_backend/src/db/starting_data.sql
  yaki_karate/src/test/resources/authenticate.feature
  yaki_karate/src/test/resources/login.feature
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.dart
Labels: bug :bug:

#199 fix(customer): updated customer table attributes
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/starting_data.sql
Labels: bug :bug:

#202 fix(customer_relation): add table customer_rights in the database
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/starting_data.sql
  yaki_database/create_tables.sql
Labels: bug :bug:

#203 Feat/crud owner
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/OwnerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CustomerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/OwnerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CustomerEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/OwnerEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/OwnerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
Labels: enhancement :rocket:

#206 Feature/customer crud
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CustomerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CustomerEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/GreetingsController.java
Labels: enhancement :rocket:

#221 Feat/halfday post
  package-lock.json
  yaki_backend/src/__test__/authenticate-service.test.ts
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/features/declaration/declaration.controller.ts
  yaki_backend/src/features/declaration/declaration.dtoIn.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/server.ts
  yaki_backend/src/utils/yakiUtils.ts
  yaki_database/create_tables.sql
  yaki_karate/src/test/resources/creationDeclaration.feature
  yaki_karate/src/test/resources/getLatestDeclaration.feature
  yaki_karate/src/test/resources/updateDeclaration.feature
Labels: enhancement :rocket:

#222 Feat/header day declaration
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
Labels: enhancement :rocket:

#196 chore(docker_push): create docker push workflow
  .github/workflows/docker push.yaml
Labels: chore :construction_worker_man:

#224 feat(declaration-front): on login in, a team mate goes to status page if he already made his daily declaration
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
Labels: enhancement :rocket:

#226 fix(dockerfile):changed dockerfile
  yaki_backend/dockerfile
Labels: bug :bug:

#238 Feat/team crud
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
Labels: enhancement :rocket:, 🚧 Technical stuff

#225 Test/crud customer
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/OwnerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CustomerEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/OwnerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/errorHandling/CustomExceptionHandler.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controller/CustomerControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controller/OwnerControllerTests.java
Labels: 🚧 Technical stuff, other

#242 test(declaration_half_day)
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
Labels: other

#247 Feat/captain crud
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CaptainModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CaptainEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CaptainService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
Labels: enhancement :rocket:

#251 chore(initialize_front): create structure
  yaki_admin/.eslintrc.cjs
  yaki_admin/.gitignore
  yaki_admin/.vscode/extensions.json
  yaki_admin/README.md
  yaki_admin/env.d.ts
  yaki_admin/index.html
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/src/App.vue
  yaki_admin/src/main.ts
  yaki_admin/src/router/index.ts
  yaki_admin/src/views/HomeView.vue
  yaki_admin/tsconfig.json
  yaki_admin/tsconfig.node.json
  yaki_admin/vite.config.ts
Labels: chore :construction_worker_man:

#240 refactor(backEnd): removed unused declaration methode and assiciated …
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/features/declaration/declaration.controller.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_karate/src/test/resources/updateDeclaration.feature
Labels: other

#262 Feat/back declaration with team
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/features/declaration/declaration.dtoIn.ts
  yaki_backend/src/features/declaration/declaration.interface.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/team/team.dtoIn.ts
  yaki_karate/src/test/resources/creationDeclaration.feature
  yaki_karate/src/test/resources/getLatestDeclaration.feature
  yaki_mobile/test/.test_optimizer.dart
Labels: enhancement :rocket:

#274 feat(admin_owner_put): add method put and test Junit for this method'
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/OwnerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/OwnerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerControllerTests.java
Labels: enhancement :rocket:

#273 fix(to_camel): change teamDtoIt interface into class, and change snak…
  yaki_backend/src/__test__/__mocks__/team.ts
  yaki_backend/src/__test__/team-service.test.ts
  yaki_backend/src/__test__/teamMates.test.ts
  yaki_backend/src/features/team/team.dtoIn.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/team/team.service.ts
  yaki_backend/src/features/teamMate/teamMate.controller.ts
  yaki_backend/src/features/teamMate/teamMate.service.ts
Labels: bug :bug:

#276 Fix/get declaration
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/displaydata/status_page_content.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.mocks.dart
Labels: bug :bug:

#277 fix team selection
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/features/team/team.repository.ts
  yaki_mobile/lib/data/repositories/team_repository.dart
Labels: bug :bug:

#278 Fix/header layout
  yaki_mobile/lib/presentation/styles/header_text_style.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.look.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/status_card.dart
  yaki_mobile/lib/presentation/ui/shared/pages_layout_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
  yaki_mobile/lib/presentation/ui/status/halfday_status.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
  yaki_mobile/test/goldens/declaration_golden_1600x1200_.png
  yaki_mobile/test/goldens/declaration_golden_400x600_.png
  yaki_mobile/test/goldens/declaration_golden_800x1200_.png
  yaki_mobile/test/goldens/declaration_golden_800x600_.png
Labels: bug :bug:

#292 chore(front_admin): folder architecture
  yaki_admin/src/assets/.gitkeep
  yaki_admin/src/features/captain/components/.gitkeep
  yaki_admin/src/features/captain/layouts/.gitkeep
  yaki_admin/src/features/captain/pages/.gitkeep
  yaki_admin/src/features/captain/services/.gitkeep
  yaki_admin/src/shared/.gitkeep
  yaki_admin/src/shared/components/.gitkeep
  yaki_admin/src/shared/layouts/.gitkeep
  yaki_admin/src/views/HomeView.vue
Labels: chore :construction_worker_man:

#297 docs(PrivacyPolicy): add privacy policy file
  PRIVACY_POLICY.md
Labels: other

#264 chore(release): create release build config for android
  .gitignore
  yaki_mobile/.vscode/launch.json
  yaki_mobile/android/app/build.gradle
  yaki_mobile/android/app/src/debug/AndroidManifest.xml
  yaki_mobile/android/app/src/main/AndroidManifest.xml
  yaki_mobile/assets/cer/.gitkeep
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/state/dio/dio_interceptor.dart
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#270 Test/owner admin
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerControllerTests.java
  yaki_karate/src/test/resources/ownerAdmin.feature
Labels: other

#279 Test/captain admin
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.java
  yaki_karate/src/test/resources/captainAdmin.feature
Labels: other
