Repository XPEHO/YAKI, pull requests merged in 2023-02, with the labels that each got.

#19 docs(contributing): create first CONTRIBUTING file
  CONTRIBUTING.md
Labels: documentation

#21 chore(ci): create base CI checks
  .github/release.yml
  .github/workflows/git_checks.yaml
  .github/workflows/labels.yaml
  README.md
Labels: chore :construction_worker_man:

#25 Chore/set up of database
  yaki_database/create_tables.sql
  yaki_database/create_user.sql
Labels: chore :construction_worker_man:

#29 feat/genericheader
  yaki_mobile/analysis_options.yaml
  yaki_mobile/assets/images/authent.png
  yaki_mobile/assets/images/authent.svg
  yaki_mobile/assets/images/dots.svg
  yaki_mobile/assets/translations/.gitkeep
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/Authentification.dart
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/appRouter.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/styles/HeaderTextStyle.dart
  yaki_mobile/lib/presentation/ui/shared/views/Header.dart
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/widget_test.dart
Labels: enhancement :rocket:

#31 Feat/authentification-back
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/dev/swagger.json
  yaki_backend/src/features/captain/captain.controller.ts
  yaki_backend/src/features/captain/captain.dtoIn.ts
  yaki_backend/src/features/captain/captain.dtoOut.ts
  yaki_backend/src/features/captain/captain.repository.ts
  yaki_backend/src/features/captain/captain.service.ts
  yaki_backend/src/features/teamMate/teamMate.dtoIn.ts
  yaki_backend/src/features/teamMate/teamMate.dtoOut.ts
  yaki_backend/src/features/teamMate/teamMate.repository.ts
  yaki_backend/src/features/teamMate/teamMate.service.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.dtoIn.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/repository.ts
  yaki_backend/src/router.ts
  yaki_backend/src/server.ts
  yaki_mobile/assets/images/HL_WP.jpeg
  yaki_mobile/assets/images/google_dino.png
  yaki_mobile/lib/Authentification.dart
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/ui/shared/views/Header.dart
Labels: enhancement :rocket:

#34 Feat/declaration back
  yaki_backend/src/declaration/DAO/DeclarationDAO.ts
  yaki_backend/src/dev/swagger.js
  yaki_backend/src/features/declaration/daclaration.controller.ts
  yaki_backend/src/features/declaration/declaration.interface.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/declaration/status.enum.ts
  yaki_backend/src/repository.ts
  yaki_backend/src/server.ts
  yaki_database/create_tables.sql
  yaki_mobile/.gitkeep
Labels: enhancement :rocket:

#35 Feat/authentification back
  yaki_backend/.dockerignore
  yaki_backend/env.sample
  yaki_backend/src/config.ts
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/create_user.ts
  yaki_backend/src/db/initdb.ts
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/features/captain/captain.repository.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/server.ts
  yaki_mobile/assets/images/HL_WP.jpeg
  yaki_mobile/assets/images/google_dino.png
  yaki_mobile/lib/Authentification.dart
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/ui/shared/views/Header.dart
Labels: enhancement :rocket:

#37 feat(declaration-front): add declaration page, riverpod for state, re…
  yaki_mobile/.gitignore
  yaki_mobile/.gitkeep
  yaki_mobile/analysis_options.yaml
  yaki_mobile/assets/images/authent.png
  yaki_mobile/assets/images/authent.svg
  yaki_mobile/assets/images/avatar1.svg
  yaki_mobile/assets/images/dots.svg
  yaki_mobile/assets/images/onsite.svg
  yaki_mobile/assets/images/remote.svg
  yaki_mobile/assets/images/unknown.svg
  yaki_mobile/assets/images/vacation.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/authentification.dart
  yaki_mobile/lib/data/models/.gitkeep
  yaki_mobile/lib/data/models/declaration_model.dart
  yaki_mobile/lib/data/models/declaration_model.g.dart
  yaki_mobile/lib/data/repositories/.gitkeep
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/.gitkeep
  yaki_mobile/lib/data/sources/declaration_api.dart
  yaki_mobile/lib/data/sources/declaration_api.g.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/state/StateStatus.dart
  yaki_mobile/lib/presentation/state/notifiers/.gitkeep
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/providers/.gitkeep
  yaki_mobile/lib/presentation/state/providers/provider.dart
  yaki_mobile/lib/presentation/styles/.gitkeep
  yaki_mobile/lib/presentation/styles/HeaderTextStyle.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/status_card.dart
  yaki_mobile/lib/presentation/ui/home/views/.gitkeep
  yaki_mobile/lib/presentation/ui/photo/views/.gitkeep
  yaki_mobile/lib/presentation/ui/shared/pages_layout.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/user/.gitkeep
  yaki_mobile/lib/temp_home.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/widget_test.dart
  yaki_mobile/translations/.gitkeep
Labels: enhancement :rocket:

#39 chore(labels): add feature case
  .github/workflows/labels.yaml
Labels: chore :construction_worker_man:

#38 Feature/declaration
  yaki_backend/README.md
  yaki_backend/env.sample
  yaki_backend/src/dev/swagger.js
  yaki_backend/src/features/declaration/daclaration.controller.ts
  yaki_backend/src/features/declaration/declaration.interface.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/declaration/status.enum.ts
  yaki_backend/src/repository.ts
  yaki_backend/src/server.ts
  yaki_database/create_tables.sql
  yaki_mobile/.gitignore
  yaki_mobile/.vscode/launch.json
  yaki_mobile/analysis_options.yaml
  yaki_mobile/assets/images/avatar1.svg
  yaki_mobile/assets/images/onsite.svg
  yaki_mobile/assets/images/remote.svg
  yaki_mobile/assets/images/unknown.svg
  yaki_mobile/assets/images/vacation.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/appRouter.dart
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/authentification.dart
  yaki_mobile/lib/data/models/.gitkeep
  yaki_mobile/lib/data/models/declaration_model.dart
  yaki_mobile/lib/data/models/declaration_model.g.dart
  yaki_mobile/lib/data/repositories/.gitkeep
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/.gitkeep
  yaki_mobile/lib/data/sources/declaration_api.dart
  yaki_mobile/lib/data/sources/declaration_api.g.dart
  yaki_mobile/lib/presentation/state/StateStatus.dart
  yaki_mobile/lib/presentation/state/notifiers/.gitkeep
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/providers/.gitkeep
  yaki_mobile/lib/presentation/state/providers/provider.dart
  yaki_mobile/lib/presentation/styles/.gitkeep
  yaki_mobile/lib/presentation/styles/color.dart
  yaki_mobile/lib/presentation/styles/header_text_style.dart
  yaki_mobile/lib/presentation/styles/theme.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/status_card.dart
  yaki_mobile/lib/presentation/ui/home/views/.gitkeep
  yaki_mobile/lib/presentation/ui/photo/views/.gitkeep
  yaki_mobile/lib/presentation/ui/shared/pages_layout.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
  yaki_mobile/lib/presentation/ui/user/.gitkeep
  yaki_mobile/lib/temp_home.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:
