Repository XPEHO/YAKI, pull requests merged in 2023-09, with the labels that each got.

#741 chore(security_xss_admin): increase xss protection and add a content …
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
Labels: security 🚨, backend-admin

#742 Fix/admin front remove user
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/services/teamList.service.ts
  yaki_admin/src/features/shared/components/UserCard.vue
  yaki_admin/src/features/shared/modal/component/ModalListDropDown.vue
  yaki_admin/src/features/shared/modal/layouts/ModalContentDeletionValidation.vue
  yaki_admin/src/features/shared/modal/services/modalState.ts
  yaki_admin/src/models/userWithId.type.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntityWithID.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateControllerTests.java
Labels: bug :bug:

#760 fix(no_declaration): creation redirection page if you are not in a team
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/user.dart
  yaki_mobile/lib/data/models/user.g.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/domain/entities/logged_user.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/default/user_default_redirection.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
  yaki_mobile/test/unit/data/models/user_test.dart
Labels: bug :bug:

#761 Feat/spring forgotten password
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/VerificationTokenModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/PasswordServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/AuthenticationService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/error_handling/CustomExceptionHandler.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/events/OnResetPasswordCompletEvent.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/EmailListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/ResetPasswordListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/AuthenticationController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/PasswordServiceImplTest.java
Labels: enhancement :rocket:, backend-admin

#763 chore/middleware_mobile
  .github/workflows/karate.yaml
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/declaration.router.ts
  yaki_backend/src/middleware/rateLimiter.ts
  yaki_backend/src/router.ts
  yaki_backend/src/team.router.ts
Labels: chore :construction_worker_man:, security 🚨

#782 feat/mobile_change_password
  yaki_backend/src/features/password/password.controller.ts
  yaki_backend/src/features/password/password.repository.ts
  yaki_backend/src/features/password/password.service.ts
  yaki_backend/src/features/password/passwordChange.dtoIn.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/yakiUtils.ts
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/password_changement_out.dart
  yaki_mobile/lib/data/models/password_changement_out.g.dart
  yaki_mobile/lib/data/repositories/password_repository.dart
  yaki_mobile/lib/data/sources/remote/password_api.dart
  yaki_mobile/lib/data/sources/remote/password_api.g.dart
  yaki_mobile/lib/presentation/state/notifiers/password_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/providers/password_provider.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/password/change_password.dart
  yaki_mobile/lib/presentation/ui/profile/profile.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
  yaki_mobile/lib/presentation/ui/registration/view/registration_snackbar.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_registration_page.dart
Labels: enhancement :rocket:

#786 fix(auth_requirement_password): change password security for changing…
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/ChangePasswordEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/ResetPasswordEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/AuthenticationService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/AuthenticationController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
Labels: bug :bug:, security 🚨

#787 Feat/reset password
  yaki_backend/src/__test__/user-service.test.ts
  yaki_backend/src/features/password/password.controller.ts
  yaki_backend/src/features/password/password.repository.ts
  yaki_backend/src/features/password/password.service.ts
  yaki_backend/src/features/password/passwordForgotten.dtoIn.ts
  yaki_backend/src/features/password/passwortChange.dtoIn.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_mobile/.vscode/launch.json
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/password_forgot_out.dart
  yaki_mobile/lib/data/models/password_forgot_out.g.dart
  yaki_mobile/lib/data/repositories/password_repository.dart
  yaki_mobile/lib/data/sources/remote/password_api.dart
  yaki_mobile/lib/data/sources/remote/password_api.g.dart
  yaki_mobile/lib/presentation/state/notifiers/password_notifier.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/default/user_default_redirection.dart
  yaki_mobile/lib/presentation/ui/password/change_password.dart
  yaki_mobile/lib/presentation/ui/password/forgot_password.dart
  yaki_mobile/lib/presentation/ui/registration/form_functionality.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
Labels: enhancement :rocket:

#788 fix(rate_limiter): increase nodeJS limiter
  yaki_backend/src/middleware/rateLimiter.ts
Labels: bug :bug:

#789 fix(admin_sidebar_redirect): revert security change
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#791 chore(matomo): add matomo basic script for web mobile
  yaki_mobile/pubspec.lock
  yaki_mobile/web/index.html
Labels: chore :construction_worker_man:

#792 chore(prod_appbundle): setup prod appbundle upload
  .github/workflows/docker push release.yaml
  .github/workflows/docker push.yaml
  .github/workflows/restart_prod.yaml
  .github/workflows/upload_appbundle_PROD.yaml
  .github/workflows/upload_appbundle_UAT.yaml
Labels: chore :construction_worker_man:

#795 fix(matomo): fix matomo url to avoid CORS errors
  yaki_mobile/web/index.html
Labels: bug :bug:

#799 fix(ci): add prefixe style for prefiwe for branche allowed
  .github/workflows/git_checks.yaml
Labels: bug :bug:

#798 style(implement-design-picto): implement picto design ui
  yaki_mobile/assets/images/Time-Afternoun.svg
  yaki_mobile/assets/images/Time-Morning.svg
  yaki_mobile/assets/images/Validated.svg
  yaki_mobile/assets/images/Work-Home.svg
  yaki_mobile/assets/images/Work-Office.svg
Labels: other

#800 feat(prometheus): add intern entry to retrieve metrics for prometheus
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/server.ts
Labels: enhancement :rocket:, chore :construction_worker_man:, production

#803 fix(flutter_version): change dependencies version and remove look
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#802 fix(revert_prometheus_admin): revert change as it brokes UAT for unex…
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
Labels: bug :bug:

#814 Style/login
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: other

#815 fix(register): correction translate
  yaki_mobile/assets/translations/fr.json
Labels: bug :bug:

#816 feat(datepicker_range): add date picker range, included date insteas …
  yaki_docker/docker-compose.yml
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
Labels: enhancement :rocket:, :iphone: mobile

#818 fix(patch_team_page): split page in widgets, review listView
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_header.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_future_provider.dart
Labels: bug :bug:

#819 fix(manifest): change bg and theme color for web
  yaki_mobile/web/manifest.json
Labels: bug :bug:

#820 fix(login-style): fix padding
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/pubspec.lock
Labels: bug :bug:

#821 feat(declaration_page_logic): first part of declaration change
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.g.dart
  yaki_mobile/lib/presentation/displaydata/declaration_enum.dart
  yaki_mobile/lib/presentation/displaydata/status_page_utils.dart
  yaki_mobile/lib/presentation/features/declaration/temp_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/declaration_single_choice.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/halfday_status_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/state/team_page_state.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.look.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.mocks.dart
  yaki_mobile/test/unit/data/repositories/team_repository_test.mocks.dart
  yaki_mobile/test/unit/data/repositories/teammate_repository_test.mocks.dart
  yaki_mobile/test/unit/mocking.mocks.dart
Labels: enhancement :rocket:

#822 fix(mobile_back): change acceptable status to add absence, remove unu…
  yaki_backend/src/features/declaration/status.enum.ts
Labels: bug :bug:

#824 feat(redesign_logic): declaration logic half day
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/displaydata/declaration_card_content.dart
  yaki_mobile/lib/presentation/displaydata/declaration_enum.dart
  yaki_mobile/lib/presentation/displaydata/status_page_utils.dart
  yaki_mobile/lib/presentation/features/declaration/temp_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/halfday_status_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/authentication/logger.dart
  yaki_mobile/lib/presentation/ui/declaration/afternoon_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/morning_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/status_card.dart
  yaki_mobile/lib/presentation/ui/shared/views/team_selection_dialog.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_fullday.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_halfday.dart
  yaki_mobile/lib/presentation/ui/status/vacation_status.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
  yaki_mobile/test/widget/authentication_widget_test.dart
Labels: enhancement :rocket:

#825 fix(team_list_reset): reset team list on status page change button press
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_fullday.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_halfday.dart
  yaki_mobile/lib/presentation/ui/status/vacation_status.dart
Labels: bug :bug:

#828 fix(cards): width and image size
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
  yaki_mobile/lib/presentation/features/declaration/temp_page.dart
Labels: bug :bug:

#826 Style/work localisation
  yaki_mobile/assets/images/Time-Afternoon.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/displaydata/declaration_card_content.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration/temp_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/pubspec.lock
Labels: other

#830 fix(absence): fix halfday absence message and text
  yaki_mobile/assets/images/absence.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/pubspec.lock
Labels: bug :bug:

#831 fix(mobile_login): redirection at sign in, and save login info by default
  yaki_mobile/lib/data/sources/local/shared_preference.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/shared/views/custom_checkbox.dart
Labels: bug :bug:

#832 fix(absence): userID refacto in declaration creation, single absence link restored
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
Labels: bug :bug:

#833 fix(back_button): fix declaration back button
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/ios/Podfile.lock
  yaki_mobile/ios/Runner.xcodeproj/project.pbxproj
  yaki_mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/ui/captain/captain_view.dart
  yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
  yaki_mobile/lib/presentation/ui/captain/views/teammate_card.dart
  yaki_mobile/lib/presentation/ui/captain/views/teammate_card_halfday.dart
  yaki_mobile/lib/presentation/ui/shared/pages_layout_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
Labels: bug :bug:
