Repository XPEHO/YAKI, pull requests merged in 2023-03, with the labels that each got.

#41 fix(header): remove duplicate file
  yaki_mobile/lib/presentation/ui/shared/views/Header.dart
Labels: bug :bug:

#40 Feat/authentication front
  .idea/YAKI.iml
  yaki_mobile/.gitignore
  yaki_mobile/.vscode/launch.json
  yaki_mobile/assets/translations/.gitkeep
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/appRouter.dart
  yaki_mobile/lib/data/models/login.dart
  yaki_mobile/lib/data/models/login.g.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/sources/login_api.dart
  yaki_mobile/lib/data/sources/login_api.g.dart
  yaki_mobile/lib/presentation/state/login_state.dart
  yaki_mobile/lib/presentation/state/notifiers/login_notifier.dart
  yaki_mobile/lib/presentation/state/providers/login_provider.dart
  yaki_mobile/lib/presentation/ui/authentication/Authentication.dart
  yaki_mobile/lib/presentation/ui/authentication/logger.dart
  yaki_mobile/lib/presentation/ui/shared/views/ButtonApp.dart
  yaki_mobile/lib/presentation/ui/shared/views/InputApp.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:

#42 Feat/authentication
  .idea/YAKI.iml
  yaki_backend/.dockerignore
  yaki_backend/README.md
  yaki_backend/env.sample
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/config.ts
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/db/create_user.ts
  yaki_backend/src/db/initdb.ts
  yaki_backend/src/db/starting_data.sql
  yaki_backend/src/dev/swagger.json
  yaki_backend/src/features/captain/captain.controller.ts
  yaki_backend/src/features/captain/captain.dtoIn.ts
  yaki_backend/src/features/captain/captain.dtoOut.ts
  yaki_backend/src/features/captain/captain.repository.ts
  yaki_backend/src/features/captain/captain.service.ts
  yaki_backend/src/features/teamMate/teamMate.dtoIn.ts
  yaki_backend/src/features/teamMate/teamMate.dtoOut.ts
  yaki_backend/src/features/teamMate/teamMate.repository.ts
  yaki_backend/src/features/teamMate/teamMate.service.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.dtoIn.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_backend/src/server.ts
  yaki_mobile/.gitignore
  yaki_mobile/.vscode/launch.json
  yaki_mobile/assets/translations/.gitkeep
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/appRouter.dart
  yaki_mobile/lib/authentification.dart
  yaki_mobile/lib/data/models/login.dart
  yaki_mobile/lib/data/models/login.g.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/sources/login_api.dart
  yaki_mobile/lib/data/sources/login_api.g.dart
  yaki_mobile/lib/presentation/state/login_state.dart
  yaki_mobile/lib/presentation/state/notifiers/login_notifier.dart
  yaki_mobile/lib/presentation/state/providers/login_provider.dart
  yaki_mobile/lib/presentation/ui/authentication/Authentication.dart
  yaki_mobile/lib/presentation/ui/authentication/logger.dart
  yaki_mobile/lib/presentation/ui/shared/views/ButtonApp.dart
  yaki_mobile/lib/presentation/ui/shared/views/InputApp.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/widget_test.dart
Labels: enhancement :rocket:

#47 chore(dependabot): create dependabot config file
  .github/dependabot.yml
Labels: chore :construction_worker_man:

#52 Fix/yaki mobile
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/appRouter.dart
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/authentification.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/shared/views/button_app.dart
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#51 chore(workflows): fix workflows for dependabot
  .github/workflows/git_checks.yaml
  .github/workflows/labels.yaml
Labels: chore :construction_worker_man:

#56 Feat/status back
  .github/workflows/git_checks.yaml
  .github/workflows/labels.yaml
  yaki_backend/README.md
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/dev/swagger.json
  yaki_backend/src/features/declaration/daclaration.controller.ts
  yaki_backend/src/features/declaration/declaration.controller.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:

#58 Feat/status back
  yaki_backend/src/features/declaration/declaration.router.ts
Labels: enhancement :rocket:

#65 fix(declaration): fixed bug
  yaki_backend/src/features/declaration/declaration.controller.ts
  yaki_backend/src/features/declaration/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.service.ts
Labels: bug :bug:

#78 chore(workflows): edit label workflow triggers
  .github/workflows/labels.yaml
Labels: chore :construction_worker_man:

#79 chore(gitattributes): ignore generated files for pull requests
  .gitattributes
Labels: chore :construction_worker_man:

#81 Feat/forv1
  yaki_backend/src/router.ts
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/authentication.dart
  yaki_mobile/lib/data/models/authentication.g.dart
  yaki_mobile/lib/data/models/captain_model.dart
  yaki_mobile/lib/data/models/captain_model.g.dart
  yaki_mobile/lib/data/models/declaration_model.dart
  yaki_mobile/lib/data/models/declaration_model.g.dart
  yaki_mobile/lib/data/models/team_mate_model.dart
  yaki_mobile/lib/data/models/team_mate_model.g.dart
  yaki_mobile/lib/data/models/user.dart
  yaki_mobile/lib/data/models/user.g.dart
  yaki_mobile/lib/data/repositories/captain_repository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/repositories/team_mate_repository.dart
  yaki_mobile/lib/data/sources/captain_api.dart
  yaki_mobile/lib/data/sources/captain_api.g.dart
  yaki_mobile/lib/data/sources/remote/login_api.dart
  yaki_mobile/lib/data/sources/remote/login_api.g.dart
  yaki_mobile/lib/domain/entities/logged_user.dart
  yaki_mobile/lib/domain/entities/team_mate_entity.dart
  yaki_mobile/lib/presentation/state/notifiers/captain_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_mate_notifier.dart
  yaki_mobile/lib/presentation/state/providers/captain_provider.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
  yaki_mobile/lib/temp_home.dart
Labels: enhancement :rocket:

#82 feat(nocrypt): remove crypt
  yaki_mobile/lib/data/repositories/login_repository.dart
Labels: enhancement :rocket:

#91 Fix/web page accessibility
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.dart
Labels: bug :bug:

#100 fix(CI prefixes): add allowed prefixes on ci
  .github/workflows/git_checks.yaml
Labels: bug :bug:

#101 docs(Dev conventions): Name and archi conventions
  CONTRIBUTING.md
Labels: other

#88 chore(karate): setup karate testing
  .github/workflows/karate.yaml
  .gitignore
  yaki_backend/src/db/starting_data.sql
  yaki_karate/pom.xml
  yaki_karate/src/main/java/org/example/Main.java
  yaki_karate/src/test/java/KarateRunner.java
  yaki_karate/src/test/resources/authenticate.feature
Labels: chore :construction_worker_man:

#120 chore(admin_backend): create admin backend structure
  .gitignore
  yaki_admin_backend/.gitignore
  yaki_admin_backend/build.gradle
  yaki_admin_backend/gradle/wrapper/gradle-wrapper.jar
  yaki_admin_backend/gradle/wrapper/gradle-wrapper.properties
  yaki_admin_backend/gradlew
  yaki_admin_backend/gradlew.bat
  yaki_admin_backend/settings.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/YakiAdminBackendApplication.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CustomerJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CustomerEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/GreetingsController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/YakiAdminBackendApplicationTests.java
Labels: chore :construction_worker_man:

#116 feat(web): manage flutter web
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/server.ts
  yaki_mobile/Dockerfile
  yaki_mobile/README.md
  yaki_mobile/pubspec.lock
Labels: enhancement :rocket:

#117 Test/karate test back
  yaki_backend/README.md
  yaki_karate/src/test/resources/authenticate.feature
  yaki_karate/src/test/resources/creationDeclaration.feature
  yaki_karate/src/test/resources/getLatestDeclaration.feature
  yaki_karate/src/test/resources/login.feature
Labels: other

#121 chore(dependabot): add admin backend and karate to dependabot scan co…
  .github/dependabot.yml
Labels: chore :construction_worker_man:

#130 refactor(httpResponse): remove httpResponse type, repo refactored acc…
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/repositories/team_mate_repository.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.g.dart
  yaki_mobile/lib/data/sources/remote/login_api.dart
  yaki_mobile/lib/data/sources/remote/login_api.g.dart
  yaki_mobile/lib/data/sources/remote/status_api.dart
  yaki_mobile/lib/data/sources/remote/team_mate_api.dart
  yaki_mobile/lib/data/sources/remote/team_mate_api.g.dart
  yaki_mobile/lib/data/sources/team_mate_api.g.dart
  yaki_mobile/lib/presentation/state/providers/team_mate_provider.dart
  yaki_mobile/pubspec.lock
Labels: other

#133 fix(declaration): add constraints to declaration table in database
  yaki_backend/src/db/create_tables.sql
  yaki_database/create_tables.sql
Labels: bug :bug:

#136 test(golden): create golden tests
  yaki_mobile/.gitignore
  yaki_mobile/.vscode/launch.json
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/flutter_test_config.dart
  yaki_mobile/test/goldens/Header.png
  yaki_mobile/test/widget_test.dart
Labels: other

#140 chore(java_build): create gradle build for java backend
  .github/workflows/test_&_build.yaml
Labels: chore :construction_worker_man:

#141 Fix/captain view
  yaki_mobile/lib/data/models/team_mate_model.dart
  yaki_mobile/lib/data/models/team_mate_model.g.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/repositories/team_mate_repository.dart
  yaki_mobile/lib/data/sources/remote/team_mate_api.dart
  yaki_mobile/lib/data/sources/remote/team_mate_api.g.dart
  yaki_mobile/lib/domain/entities/logged_user.dart
  yaki_mobile/lib/domain/entities/team_mate_entity.dart
  yaki_mobile/lib/presentation/state/notifiers/team_mate_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_mate_provider.dart
  yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
  yaki_mobile/test/widget_test.mocks.dart
Labels: bug :bug:

#154 Test/jest get team mate
  yaki_backend/.gitignore
  yaki_backend/babel.config.js
  yaki_backend/src/__test__/__mocks__/team.ts
  yaki_backend/src/__test__/__mocks__/teamMate.ts
  yaki_backend/src/__test__/__mocks__/teamMateWithDeclaration.ts
  yaki_backend/src/__test__/teamMates.test.ts
  yaki_backend/src/features/teamMate/teamMate.dtoIn.ts
  yaki_backend/src/features/teamMate/teamMate.service.ts
  yaki_backend/src/features/user/user.dtoIn.ts
  yaki_backend/tsconfig.json
Labels: other

#155 Test/declaration jest
  yaki_backend/src/__test__/__mocks__/user.ts
  yaki_backend/src/__test__/authenticate-service.test.ts
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/__test__/user-service.test.ts
  yaki_backend/src/features/user/authentication.service.ts
  yaki_backend/tsconfig.json
Labels: other

#160 fix(user login): Can create a teamMate/captain without a valid user
  yaki_backend/src/db/create_tables.sql
  yaki_database/create_tables.sql
Labels: bug :bug:

#162 Test/captain service
  yaki_backend/src/__test__/__mocks__/captain.ts
  yaki_backend/src/__test__/captain-service.test.ts
Labels: other

#167 Test/flutter unit test
  yaki_mobile/.gitignore
  yaki_mobile/dart_test.yaml
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/login.dart
  yaki_mobile/lib/data/models/login_model.dart
  yaki_mobile/lib/data/models/login_model.g.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/repositories/team_mate_repository.dart
  yaki_mobile/lib/data/sources/local/shared_preference.dart
  yaki_mobile/lib/data/sources/remote/login_api.dart
  yaki_mobile/lib/domain/entities/team_mate_entity.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
  yaki_mobile/test/unit/data/models/declaration_model_in_test.dart
  yaki_mobile/test/unit/data/models/declaration_model_test.dart
  yaki_mobile/test/unit/data/models/login_model_test.dart
  yaki_mobile/test/unit/data/models/team_mate_model_test.dart
  yaki_mobile/test/unit/data/models/user_test.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.dart
  yaki_mobile/test/unit/data/repositories/login_repository_test.mocks.dart
  yaki_mobile/test/unit/data/repositories/team_mate_repository_test.dart
  yaki_mobile/test/unit/data/repositories/team_mate_repository_test.mocks.dart
  yaki_mobile/test/unit/data/sources/local/shared_preference_test.dart
  yaki_mobile/test/unit/mocking.dart
  yaki_mobile/test/unit/mocking.mocks.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.mocks.dart
Labels: other

#166 test(updateDeclaration_jext)
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_karate/src/test/resources/updateDeclaration.feature
Labels: other

#169 docs(flutter_doc): documentation creation
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/sources/local/shared_preference.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/state/dio/dio_interceptor.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/providers/login_provider.dart
  yaki_mobile/lib/presentation/state/providers/status_provider.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/test/unit/data/models/declaration_model_in_test.dart
  yaki_mobile/test/unit/data/models/declaration_model_test.dart
  yaki_mobile/test/unit/data/models/login_model_test.dart
  yaki_mobile/test/unit/data/models/team_mate_model_test.dart
  yaki_mobile/test/unit/data/models/user_test.dart
  yaki_mobile/test/unit/mocking.dart
Labels: other

#172 Fix/declaration status
  yaki_backend/src/__test__/declaration-service.test.ts
  yaki_backend/src/__test__/teamMates.test.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_backend/src/features/declaration/status.enum.ts
  yaki_karate/src/test/resources/creationDeclaration.feature
  yaki_karate/src/test/resources/getLatestDeclaration.feature
  yaki_karate/src/test/resources/updateDeclaration.feature
Labels: bug :bug:

#181 Refactor/create status page content
  yaki_backend/src/features/declaration/status.enum.ts
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/repositories/login_repository.dart
  yaki_mobile/lib/data/sources/local/shared_preference.dart
  yaki_mobile/lib/presentation/displaydata/declaration_card_content.dart
  yaki_mobile/lib/presentation/displaydata/status_page_content.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
  yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
Labels: other

#183 fix(database-translation)
  yaki_backend/src/db/starting_data.sql
  yaki_mobile/assets/images/onSite.svg
  yaki_mobile/lib/presentation/displaydata/declaration_card_content.dart
Labels: bug :bug:
