Repository XPEHO/YAKI, pull requests merged in 2023-07, with the labels that each got.

#526 docs(yaki-mobile): add documentations and change default color variable for the whole app
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_mate_provider.dart
  yaki_mobile/lib/presentation/styles/color.dart
  yaki_mobile/lib/presentation/styles/header_text_style.dart
  yaki_mobile/lib/presentation/styles/theme.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
  yaki_mobile/lib/presentation/ui/captain/views/team_mate_card_halfday.dart
  yaki_mobile/lib/presentation/ui/declaration/views/afternoon_declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
  yaki_mobile/lib/presentation/ui/declaration/views/morning_declaration_body.dart
  yaki_mobile/lib/presentation/ui/shared/views/button_app.dart
  yaki_mobile/lib/presentation/ui/shared/views/custom_checkbox.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_with_label_app.dart
  yaki_mobile/lib/presentation/ui/status/halfday_status.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
Labels: other

#528 feat(vue3_remove_user_team): create feature to delete a teammate from a team
  yaki_admin/src/App.vue
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/teamMate.vue
  yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
  yaki_admin/src/features/captain/services/isActiveTeam.ts
  yaki_admin/src/features/invitation/components/UserComponent.vue
  yaki_admin/src/features/invitation/layouts/LayoutInvitation.vue
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/features/shared/components/ConfirmModal.vue
  yaki_admin/src/features/shared/services/modalState.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/src/stores/teamStore.ts
Labels: enhancement :rocket:

#532 fix(vue3): correct captain id to fetch team
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
Labels: bug :bug:

#533 feat(admin_cpt_team): add team - edit - delete feature
  yaki_admin/src/envPlaceholder.ts
  yaki_admin/src/features/PageApplication.vue
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/components/TeamListElement.vue
  yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
  yaki_admin/src/features/captain/services/isActiveTeam.ts
  yaki_admin/src/features/invitation/layouts/LayoutInvitation.vue
  yaki_admin/src/features/shared/components/ModalTeam.vue
  yaki_admin/src/features/shared/components/ModalValidation.vue
  yaki_admin/src/features/shared/services/modalTeamState.ts
  yaki_admin/src/features/shared/services/modalValidationState.ts
  yaki_admin/src/main.ts
  yaki_admin/src/models/team.type.ts
  yaki_admin/src/models/teamMate.type.ts
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/services/teamMate.service.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Labels: enhancement :rocket:

#535 fix(admin_modal_btn_color): use correct color for boutons
  yaki_admin/src/features/shared/components/ModalTeam.vue
  yaki_admin/src/features/shared/components/ModalValidation.vue
Labels: bug :bug:

#536 chore(change-flutter-version): upgrade flutter version to 1.4.0
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#537 Chore/change flutter version
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#538 Chore/change flutter version
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#554 fix(docker_push_admin_backend): add test properties to build correctl…
  .github/workflows/docker push.yaml
Labels: bug :bug:

#559 fix(admin_front_search_teammates): add token for search user bar
  yaki_admin/src/services/users.service.ts
Labels: bug :bug:

#561 Fix/admin front search teammates
  yaki_admin/src/services/users.service.ts
Labels: bug :bug:

#562 Feat/api mobile registration route
  yaki_backend/src/features/user/registerResponse.ts
  yaki_backend/src/features/user/toRegister.dtoIn.ts
  yaki_backend/src/features/user/toRegister.dtoOut.ts
  yaki_backend/src/features/user/toRegisterRes.dto.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/yakiUtils.ts
Labels: enhancement :rocket:

#565 Test/karate connect database
  .github/workflows/karate.yaml
  yaki_karate/.gitignore
  yaki_karate/pom.xml
  yaki_karate/src/main/java/org/example/utils/DbUtils.java
  yaki_karate/src/test/resources/adminAuthenticate.feature
Labels: 🗄️ database, test 🛠️

#574 Feat/mobile sign in page
  yaki_backend/src/features/user/toRegisterResponse.dto.ts
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/user_registration_model.dart
  yaki_mobile/lib/data/models/user_registration_model.g.dart
  yaki_mobile/lib/data/repositories/user_registration_service.dart
  yaki_mobile/lib/data/sources/remote/user_register_repository.dart
  yaki_mobile/lib/data/sources/remote/user_register_repository.g.dart
  yaki_mobile/lib/domain/entities/user_registered.dart
  yaki_mobile/lib/domain/entities/user_registered.g.dart
  yaki_mobile/lib/presentation/state/providers/login_provider.dart
  yaki_mobile/lib/presentation/state/providers/user_registration_provider.dart
  yaki_mobile/lib/presentation/styles/header_text_style.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
  yaki_mobile/lib/presentation/ui/registration/view/registration_snackbar.dart
  yaki_mobile/lib/presentation/ui/shared/views/confirmation_elevated_button.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_registration_page.dart
  yaki_mobile/lib/presentation/ui/status/halfday_status.dart
  yaki_mobile/lib/presentation/ui/status/status.dart
  yaki_mobile/test/unit/presentation/state/notifiers/declaration_notifier_test.mocks.dart
Labels: enhancement :rocket:

#575 fix(declaration_switch): set declaration mode button switch more visible
  yaki_mobile/assets/images/switch.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/ui/declaration/afternoon_declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/declaration.dart
  yaki_mobile/lib/presentation/ui/declaration/morning_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
  yaki_mobile/lib/presentation/ui/shared/views/input_registration_page.dart
Labels: bug :bug:, enhancement :rocket:, :iphone: mobile

#572 Feature/inscription mailjet back admin
  yaki_admin_backend/README.md
  yaki_admin_backend/build.gradle
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/VerificationTokenModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/VerificationTokenServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/VerificationTokenJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/AuthenticationResponseEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/RegisterResponseEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/AuthenticationService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/VerificationTokenService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/error_handling/CustomExceptionHandler.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/error_handling/EmailAlreadyExistsException.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/events/OnRegistrationCompleteEvent.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/AuthenticationController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/features/user/toRegisterResponse.dto.ts
  yaki_karate/src/test/resources/adminAuthenticate.feature
Labels: enhancement :rocket:

#580 fix(mobile_registration_cancel): create cancel button for registration page
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
  yaki_mobile/lib/presentation/ui/shared/views/confirmation_elevated_button.dart
Labels: bug :bug:

#582 fix(registration_text): fix french text not displaying for password
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#592 chore(sonar): add flutter scan
  .github/workflows/sonar.yaml
  yaki_mobile/sonar-project.properties
  yaki_mobile/test/fake_test.dart
Labels: chore :construction_worker_man:

#632 Feat/path customer rights
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CustomerRightsEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
Labels: enhancement :rocket:

#637 chore(DoR-template): adding template with DOR
  .github/ISSUE_TEMPLATE/dor_issue_template.md
Labels: chore :construction_worker_man:

#639 Fix/mobile login remove avatar
  yaki_mobile/lib/presentation/ui/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/shared/views/avatar_icon.dart
  yaki_mobile/lib/presentation/ui/shared/views/header.dart
Labels: bug :bug:

#650 test(widget): add widget test example
  yaki_mobile/lib/presentation/ui/shared/views/input_app.dart
  yaki_mobile/test/unit/data/repositories/team_repository_test.dart
  yaki_mobile/test/unit/data/repositories/team_repository_test.mocks.dart
  yaki_mobile/test/widget/authentication_widget_test.dart
Labels: other

#649 fix(remove_unused_flutter_plateform): remove linux macos windows
  yaki_mobile/linux/.gitignore
  yaki_mobile/linux/CMakeLists.txt
  yaki_mobile/linux/flutter/CMakeLists.txt
  yaki_mobile/linux/flutter/generated_plugin_registrant.cc
  yaki_mobile/linux/flutter/generated_plugin_registrant.h
  yaki_mobile/linux/flutter/generated_plugins.cmake
  yaki_mobile/linux/main.cc
  yaki_mobile/linux/my_application.cc
  yaki_mobile/linux/my_application.h
  yaki_mobile/macos/.gitignore
  yaki_mobile/macos/Flutter/Flutter-Debug.xcconfig
  yaki_mobile/macos/Flutter/Flutter-Release.xcconfig
  yaki_mobile/macos/Flutter/GeneratedPluginRegistrant.swift
  yaki_mobile/macos/Podfile
  yaki_mobile/macos/Podfile.lock
  yaki_mobile/macos/Runner.xcodeproj/project.pbxproj
  yaki_mobile/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  yaki_mobile/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  yaki_mobile/macos/Runner.xcworkspace/contents.xcworkspacedata
  yaki_mobile/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  yaki_mobile/macos/Runner/AppDelegate.swift
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  yaki_mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  yaki_mobile/macos/Runner/Base.lproj/MainMenu.xib
  yaki_mobile/macos/Runner/Configs/AppInfo.xcconfig
  yaki_mobile/macos/Runner/Configs/Debug.xcconfig
  yaki_mobile/macos/Runner/Configs/Release.xcconfig
  yaki_mobile/macos/Runner/Configs/Warnings.xcconfig
  yaki_mobile/macos/Runner/DebugProfile.entitlements
  yaki_mobile/macos/Runner/Info.plist
  yaki_mobile/macos/Runner/MainFlutterWindow.swift
  yaki_mobile/macos/Runner/Release.entitlements
  yaki_mobile/windows/.gitignore
  yaki_mobile/windows/CMakeLists.txt
  yaki_mobile/windows/flutter/CMakeLists.txt
  yaki_mobile/windows/flutter/generated_plugin_registrant.cc
  yaki_mobile/windows/flutter/generated_plugin_registrant.h
  yaki_mobile/windows/flutter/generated_plugins.cmake
  yaki_mobile/windows/runner/CMakeLists.txt
  yaki_mobile/windows/runner/Runner.rc
  yaki_mobile/windows/runner/flutter_window.cpp
  yaki_mobile/windows/runner/flutter_window.h
  yaki_mobile/windows/runner/main.cpp
  yaki_mobile/windows/runner/resource.h
  yaki_mobile/windows/runner/resources/app_icon.ico
  yaki_mobile/windows/runner/runner.exe.manifest
  yaki_mobile/windows/runner/utils.cpp
  yaki_mobile/windows/runner/utils.h
  yaki_mobile/windows/runner/win32_window.cpp
  yaki_mobile/windows/runner/win32_window.h
Labels: bug :bug:
