Repository XPEHO/YAKI, pull requests merged in 2023-12, with the labels that each got.

#1146 feat(description_team_front): fetch description
  yaki_admin/README.md
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/customer/components/TeamWithCaptainCard.vue
  yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue
  yaki_admin/src/features/modal/services/modalState.ts
  yaki_admin/src/models/team.type.ts
  yaki_admin/src/services/team.service.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamEntity.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamControllerTests.java
  yaki_karate/src/test/resources/adminTeam.feature
Labels: enhancement :rocket:

#1159 refactor(ui_archi): regroup visual .vue into ui folder
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/customer/CustomerPage.vue
  yaki_admin/src/features/customer/components/CaptainDropDown.vue
  yaki_admin/src/features/customer/components/SideBarCustomer.vue
  yaki_admin/src/features/customer/components/TeamWithCaptainCard.vue
  yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/features/login/LoginView.vue
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/router/router.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin/src/ui/components/LoggedUserCard.vue
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/UserList.vue
  yaki_admin/src/ui/components/buttons/ButtonIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonPrimary.vue
  yaki_admin/src/ui/components/buttons/ButtonSecondary.vue
  yaki_admin/src/ui/components/buttons/ButtonTextIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonTextSized.vue
  yaki_admin/src/ui/components/inputs/InputPassword.vue
  yaki_admin/src/ui/components/inputs/InputText.vue
  yaki_admin/src/ui/components/inputs/InputTextArea.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/components/modals/ModalDelete.vue
  yaki_admin/src/ui/components/modals/ModalTeamEditDelete.vue
  yaki_admin/src/ui/components/sidebar/SideBarContent.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDownElement.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuLink.vue
  yaki_admin/src/ui/layouts/PageContentLayout.vue
  yaki_admin/src/ui/layouts/PageGeneralLayout.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
  yaki_admin/src/ui/views/captain/CaptainNoTeamView.vue
  yaki_admin/src/ui/views/captain/CaptainView.vue
  yaki_admin/src/ui/views/captain/PageContentHeader.vue
  yaki_admin/src/ui/views/customer/CustomerCaptainsView.vue
Labels: other

#1163 feat(admin_avatar): retrive user avatar to display them in team or captain list
  yaki_admin/src/assets/images/avatarF.svg
  yaki_admin/src/assets/images/avatarH.svg
  yaki_admin/src/assets/images/avatarN.svg
  yaki_admin/src/constants/avatar.enum.ts
  yaki_admin/src/constants/componentsSettings.enum.ts
  yaki_admin/src/constants/modalMode.enum.ts
  yaki_admin/src/constants/pathParam.enum.ts
  yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/features/invitation/services/invitationService.ts
  yaki_admin/src/features/modal/services/modalState.ts
  yaki_admin/src/features/shared/components/UserCard.vue
  yaki_admin/src/models/userWithId.type.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/buttons/ButtonIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonPrimary.vue
  yaki_admin/src/ui/components/buttons/ButtonSecondary.vue
  yaki_admin/src/ui/components/buttons/ButtonTextIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonTextSized.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/components/modals/ModalDelete.vue
  yaki_admin/src/ui/components/modals/ModalTeamEditDelete.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/views/CaptainsManagementView.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
  yaki_admin/src/ui/views/PageContentHeader.vue
  yaki_admin/src/ui/views/TeamManagementView.vue
  yaki_admin/src/utils/images.utils.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/dto/UserWithDetailsDto.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/AvatarModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntityWithID.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainControllerTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeammateControllerTests.java
  yaki_karate/src/test/resources/adminOwner.feature
Labels: enhancement :rocket:

#1170 fix(user_avatars): fix error in user with avatar fetch crashing if thee avatar reference was null
  yaki_admin/src/models/userWithId.type.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
Labels: bug :bug:

#1171 test(update): updated findAllByTeam test to consider a case with avatarReference null
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
Labels: other

#1172 refactor(avatar function): directly return avatar instead of waiting for the entier switch process to return the value
  yaki_admin/src/utils/images.utils.ts
Labels: other

#1169 feat(admin-front-modal-coming-soon): add coming soon for feature not …
  yaki_admin/src/router/router.ts
  yaki_admin/src/ui/components/LoggedUserCard.vue
  yaki_admin/src/ui/views/ProfileView.vue
  yaki_admin/src/ui/views/SideBarContent.vue
  yaki_admin/src/ui/views/StatisticsView.vue
Labels: enhancement :rocket:

#1173 Feat/popup comingsoon
  yaki_admin/src/constants/modalMode.enum.ts
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/modals/ModalComingSoon.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
Labels: enhancement :rocket:
