Repository XPEHO/YAKI, pull requests merged in 2023-10, with the labels that each got.

#848 refactor(declaration): remove all unnecessary declaration pages
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/domain/entities/chip_content.dart
  yaki_mobile/lib/domain/entities/location_card_content.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_provider.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: other

#849 fix(authentication): add SignleChildScroolView
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
Labels: bug :bug:

#850 feat/redesign_summary_declaration_page
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/domain/entities/summary_half_day_content.dart
  yaki_mobile/lib/presentation/displaydata/declaration_summary_enum.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration_summary/declaration_summary.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_chips_duo.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_half_day.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/halfday_status_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/providers/halfday_status_provider.dart
  yaki_mobile/lib/presentation/state/providers/status_provider.dart
  yaki_mobile/lib/presentation/styles/color.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_fullday.dart
  yaki_mobile/lib/presentation/ui/status/status_recap_halfday.dart
Labels: enhancement :rocket:

#851 refactor(declaraton): change halfday data saving, replace chip svg for constant size
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/displaydata/status_page_utils.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/features/declaration_summary/declaration_summary.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_chips_duo.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_half_day.dart
  yaki_mobile/lib/presentation/features/shared/chip_svg_picture.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/vacation_status_notifier.dart
Labels: other

#852 fix(authentication): Center the widget
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
Labels: bug :bug:

#856 fix(mobile): get latest declaration logic.
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/domain/entities/delcaration_entity_in.dart
  yaki_mobile/lib/presentation/displaydata/status_page_utils.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
Labels: bug :bug:

#858 chore(appbundle): update appbundle worklows
  .github/workflows/upload_appbundle_PROD.yaml
  .github/workflows/upload_appbundle_UAT.yaml
  yaki_mobile/pubspec.yaml
Labels: chore :construction_worker_man:

#859 fix(server_connection): fix server connection
  .github/workflows/docker push release.yaml
  .github/workflows/docker push.yaml
  .github/workflows/upload_appbundle_PROD.yaml
  .github/workflows/upload_appbundle_UAT.yaml
  yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
  yaki_mobile/lib/presentation/state/providers/login_provider.dart
  yaki_mobile/lib/presentation/state/providers/password_provider.dart
  yaki_mobile/lib/presentation/state/providers/url_provider.dart
  yaki_mobile/lib/presentation/state/providers/user_registration_provider.dart
Labels: bug :bug:

#860 fix(url_provider): use origin instead of base
  yaki_mobile/lib/presentation/state/providers/url_provider.dart
Labels: bug :bug:

#861 fix(url): fix team url
  yaki_mobile/lib/presentation/state/providers/team_provider.dart
  yaki_mobile/lib/presentation/state/providers/teammate_provider.dart
Labels: bug :bug:

#839 fix(review): issues from sprint review
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/styles/color.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
Labels: bug :bug:

#863 fix(location_card): fix incorrect status association, add absence image
  yaki_mobile/assets/images/absent.svg
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_half_day.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/state/notifiers/vacation_status_notifier.dart
Labels: bug :bug:

#874 fix(regexName): add 'ç' and '-' to the regex
  yaki_mobile/lib/presentation/ui/registration/form_functionality.dart
Labels: bug :bug:

#875 fix(queryTeamMates): split query & create service
  yaki_backend/src/__test__/teammate.test.ts
  yaki_backend/src/features/team/team.controller.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/team/team.service.ts
  yaki_backend/src/features/teammate/teammate.controller.ts
  yaki_backend/src/features/teammate/teammate.repository.ts
  yaki_backend/src/features/teammate/teammate.service.ts
  yaki_backend/src/features/teammate/teammateWithDeclaration.dtoOut.ts
  yaki_karate/src/test/resources/captainGetTeamate.feature
  yaki_karate/src/test/resources/getTeamMates.feature
Labels: bug :bug:

#876 Chore/beautiful email
  yaki_admin/src/assets/images/error-404.png
  yaki_admin/src/features/registrationConfirmation/RegistrationConfirmationPage.vue
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/register.service.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/EmailListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
Labels: chore :construction_worker_man:, 🖥 Desktop

#877 refactor(mobile_back): getTeammatewithDecalration
  yaki_backend/src/__test__/teammate.test.ts
  yaki_backend/src/features/teammate/teammate.controller.ts
  yaki_backend/src/features/teammate/teammate.repository.ts
  yaki_backend/src/features/teammate/teammate.service.ts
  yaki_backend/src/features/teammate/userWithDeclaration.dtoOut.ts
  yaki_backend/src/router.ts
  yaki_karate/src/test/resources/captainGetTeamate.feature
  yaki_karate/src/test/resources/declaration.feature
  yaki_karate/src/test/resources/getTeamMates.feature
Labels: other

#880 Feat/summary absence
  yaki_mobile/README.md
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/declaration_summary/declaration_summary.dart
  yaki_mobile/lib/presentation/features/declaration_summary/view/summary_absence.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
  yaki_mobile/pubspec.lock
Labels: bug :bug:, enhancement :rocket:, :iphone: mobile

#884 fix(registration_redirection): the redirection to confirm your accoun…
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/EmailListener.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
Labels: bug :bug:

#890 feat(LoginPage): Add Yaki Logo to Login Page
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
Labels: enhancement :rocket:

#888 feature(ModalComing): Create modal for unusable button
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Labels: enhancement :rocket:

#889 Create issue_form.yml
  .github/ISSUE_TEMPLATE/issue_form.yml
Labels: chore :construction_worker_man:

#891 feat(displayTimeSinceDeclaration): Add method to calculate time
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Labels: enhancement :rocket:

#886 fix(nameValidatorRegex): change the regex
  yaki_mobile/lib/presentation/ui/registration/form_functionality.dart
Labels: bug :bug:

#887 fix(translation): Change UpperCase to LowerCase
  yaki_mobile/assets/translations/fr.json
Labels: bug :bug:

#893 fix(manifest): update description
  yaki_mobile/web/manifest.json
Labels: bug :bug:

#892 fix(ChipsSize): increase size of chips
  yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_chips_row.dart
Labels: bug :bug:

#894 feat(PrivatePolicy): add text and link
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:

#896 fix(UI): updated yaki_ui components with proper values
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_iconchips.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/view/summary_chips_duo.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#897 fix(mobile): remove subtitle, set proper button for user declaration page
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart
Labels: bug :bug:

#911 Feature/splash screen
  yaki_mobile/assets/images/Group.png
  yaki_mobile/assets/images/splashscreen.svg
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/styles/color.dart
Labels: enhancement :rocket:

#912 fix(test): test correction and remove unused files
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_iconchips.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/view/summary_chips_duo.dart
  yaki_mobile/lib/presentation/state/notifiers/teammate_notifier.dart
  yaki_mobile/lib/presentation/state/providers/teammate_provider.dart
  yaki_mobile/test/unit/data/repositories/team_repository_test.dart
  yaki_mobile/test/unit/data/repositories/team_repository_test.mocks.dart
Labels: bug :bug:

#916 fix(err_msg): create err message for team list and teammate declaration summary
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/shared/something_went_wrong.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/teammates_list_async.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
Labels: bug :bug:

#919 fix(avatar): clean assets and change avatar
  yaki_mobile/assets/images/Avatar.svg
  yaki_mobile/assets/images/Group.png
  yaki_mobile/assets/images/absence.svg
  yaki_mobile/assets/images/authent.png
  yaki_mobile/assets/images/authent.svg
  yaki_mobile/assets/images/avatar1.svg
  yaki_mobile/assets/images/captain.svg
  yaki_mobile/assets/images/day.svg
  yaki_mobile/assets/images/dots.svg
  yaki_mobile/assets/images/exit.svg
  yaki_mobile/assets/images/moon.svg
  yaki_mobile/assets/images/pm.svg
  yaki_mobile/assets/images/remote.svg
  yaki_mobile/assets/images/sun.svg
  yaki_mobile/assets/images/switch.svg
  yaki_mobile/assets/images/vacation.svg
  yaki_mobile/assets/images/yaki_icon.png
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Labels: bug :bug:

#920 fix(team_fetch_error): change err throw in the team repository
  yaki_mobile/lib/data/repositories/team_repository.dart
  yaki_mobile/lib/presentation/state/providers/url_provider.dart
Labels: bug :bug:

#921 fix(caseSensitive): fix email case sensitive
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
Labels: bug :bug:

#922 refactor(signin_email): change sign_in email style
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
Labels: other

#925 Feat/profil page
  yaki_mobile/assets/images/Edit.svg
  yaki_mobile/assets/images/avatar-damier.svg
  yaki_mobile/assets/images/avatar-men.svg
  yaki_mobile/assets/images/avatar-men2.svg
  yaki_mobile/assets/images/avatar-woman.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
  yaki_mobile/lib/presentation/ui/profile/profile.dart
Labels: enhancement :rocket:

#929 feat(RoutageSplash): Routage splashScreen
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/main.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
Labels: enhancement :rocket:

#930 fix(redirection): delete useless route
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
Labels: bug :bug:

#931 fix(scroll-profil): add scroll in profil page
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#932 fix(Router): fix wrong named route
  yaki_mobile/lib/app_router.dart
Labels: bug :bug:

#933 fix(restart_full): setup restart_full instead of restart_uat
  .github/workflows/restart_uat.yaml
Labels: bug :bug:

#936 fix(Svg): fix svg transparancy and route
  yaki_mobile/assets/images/Avatar.svg
  yaki_mobile/assets/images/avatar-men.svg
  yaki_mobile/assets/images/avatar-men2.svg
  yaki_mobile/assets/images/avatar-woman.svg
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Labels: bug :bug:

#940 fix(logout): deleteToken when logout
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#942 fix(avatar-scroolbar): add coming soon for change avatar and fix scro…
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
Labels: bug :bug:

#943 fix(Redirection): delete splashscreen redirection
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/ui/password/change_password.dart
  yaki_mobile/lib/presentation/ui/password/forgot_password.dart
Labels: bug :bug:

#948 Fix/fetch profil page
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#945 fix(icon-edit): add icon edit
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#954 fix(page_style): remove location card sizeBox constraint causing overflow issue
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#955 Fix/redirection and loader
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/ui/status/vacation_status.dart
Labels: bug :bug:

#956 feat(feedback): create fonctionnality feedback user in login page and…
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/shared/feedback_user.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
Labels: enhancement :rocket:

#973 fix(mobile_back): prevent back query to also retrive informations not activated account
  yaki_backend/src/features/teammate/teammate.repository.ts
Labels: bug :bug:

#978 fix(back_mobile): fix to change the one day planned absence
  yaki_backend/src/features/teammate/teammate.repository.ts
Labels: bug :bug:

#975 Feat/add back button
  yaki_mobile/lib/presentation/ui/password/forgot_password.dart
  yaki_mobile/lib/presentation/ui/registration/registration.dart
Labels: enhancement :rocket:, :iphone: mobile

#976 fix(ForgotPasswordTheme): add good button
  yaki_mobile/lib/presentation/ui/password/forgot_password.dart
Labels: bug :bug:

#980 fix(addMailFeedBack): add message for user with
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/shared/feedback_user.dart
Labels: bug :bug:

#979 fix(back_mobile): the teammates summary page can display undeclared while its not
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.service.ts
Labels: bug :bug:

#982 Fix/profil page notifier
  yaki_backend/package-lock.json
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_mobile/lib/data/models/user.dart
  yaki_mobile/lib/data/models/user_info_profile.dart
  yaki_mobile/lib/data/models/user_info_profile.g.dart
  yaki_mobile/lib/data/repositories/user_repository.dart
  yaki_mobile/lib/data/sources/remote/user_api.dart
  yaki_mobile/lib/data/sources/remote/user_api.g.dart
  yaki_mobile/lib/domain/entities/user_entity.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
  yaki_mobile/lib/presentation/state/notifiers/user_notifier.dart
  yaki_mobile/lib/presentation/state/providers/user_provider.dart
Labels: bug :bug:
