Repository XPEHO/YAKI, pull requests merged in 2023-11, with the labels that each got.

#1001 fix(notifier-profil-page): replace read for watch
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#1004 fix(enabled-input-text): add enabled input text
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#1005 Feat/filter
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/domain/entities/filter_entity.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/modal_filter.dart
  yaki_mobile/lib/presentation/state/notifiers/filter_notifier.dart
  yaki_mobile/lib/presentation/state/providers/filter_provider.dart
  yaki_mobile/lib/presentation/state/providers/teammate_future_provider.dart
  yaki_mobile/lib/presentation/state/providers/teammate_provider.dart
Labels: enhancement :rocket:

#1009 feat(back_picture_save): save process of the user selected avatar
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/features/user/avatar.dto.ts
  yaki_backend/src/features/user/avatar.enum.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/yakiUtils.ts
Labels: enhancement :rocket:

#1012 feat(back_picture): do not save default avatar in the database
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/features/user/userInformations.dto.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/PictureProcessing.ts
  yaki_backend/src/utils/yakiUtils.ts
Labels: enhancement :rocket:

#1013 Feat/profil picture fetch
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/features/user/userInformations.dto.ts
  yaki_backend/uploads/1124711b746dc0de024ba0fbb2a4963f
  yaki_backend/uploads/1f0ffbf53c7b9347cf4cc14a61e70250
  yaki_backend/uploads/2e31384cc7d8baabd744875f00252968
  yaki_backend/uploads/613f54dafc595eac43570a942ce8bd71
  yaki_backend/uploads/7da9f0d5cf3b7f4337c66ba83a7b7757
  yaki_backend/uploads/9ace29ac79fd8e827d733143d4ca66b4
  yaki_backend/uploads/e0302e37af7acd041d1d034a2ef1ac54
  yaki_mobile/lib/data/models/message.dart
  yaki_mobile/lib/data/models/message.g.dart
  yaki_mobile/lib/data/models/user.dart
  yaki_mobile/lib/data/models/user_info_profile.dart
  yaki_mobile/lib/data/models/user_info_profile.g.dart
  yaki_mobile/lib/data/repositories/avatar_repository.dart
  yaki_mobile/lib/data/repositories/user_repository.dart
  yaki_mobile/lib/data/sources/remote/avatar_api.dart
  yaki_mobile/lib/data/sources/remote/avatar_api.g.dart
  yaki_mobile/lib/domain/entities/avatar_entity.dart
  yaki_mobile/lib/presentation/displaydata/avatar_enum.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
  yaki_mobile/lib/presentation/state/notifiers/avatar_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/user_notifier.dart
  yaki_mobile/lib/presentation/state/providers/avatar_provider.dart
Labels: enhancement :rocket:

#1015 Feature/mobile profil picture
  yaki_backend/package-lock.json
  yaki_backend/package.json
  yaki_backend/src/db/create_tables.sql
  yaki_backend/src/features/user/avatar.dto.ts
  yaki_backend/src/features/user/avatar.enum.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/features/user/userInformations.dto.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/PictureProcessing.ts
  yaki_backend/uploads/1124711b746dc0de024ba0fbb2a4963f
  yaki_backend/uploads/1f0ffbf53c7b9347cf4cc14a61e70250
  yaki_backend/uploads/2e31384cc7d8baabd744875f00252968
  yaki_backend/uploads/613f54dafc595eac43570a942ce8bd71
  yaki_backend/uploads/7da9f0d5cf3b7f4337c66ba83a7b7757
  yaki_backend/uploads/9ace29ac79fd8e827d733143d4ca66b4
  yaki_backend/uploads/e0302e37af7acd041d1d034a2ef1ac54
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/ios/Runner/Info.plist
  yaki_mobile/lib/data/models/message.dart
  yaki_mobile/lib/data/models/message.g.dart
  yaki_mobile/lib/data/models/user.dart
  yaki_mobile/lib/data/models/user_info_profile.dart
  yaki_mobile/lib/data/models/user_info_profile.g.dart
  yaki_mobile/lib/data/repositories/avatar_repository.dart
  yaki_mobile/lib/data/repositories/user_repository.dart
  yaki_mobile/lib/data/sources/remote/avatar_api.dart
  yaki_mobile/lib/data/sources/remote/avatar_api.g.dart
  yaki_mobile/lib/domain/entities/avatar_entity.dart
  yaki_mobile/lib/presentation/displaydata/avatar_enum.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
  yaki_mobile/lib/presentation/state/notifiers/avatar_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/user_notifier.dart
  yaki_mobile/lib/presentation/state/providers/avatar_provider.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:

#1038 fix(ProfilUserFetchAvatar): change rendering
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#1039 fix(TeamDeclarationSummaryPadding): add bottom pad
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Labels: bug :bug:

#1032 Fix/mobile get user avatar
  yaki_backend/src/features/user/user.service.ts
  yaki_mobile/lib/data/repositories/avatar_repository.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
Labels: bug :bug:

#1040 feat(Error): add profil and change redirection
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
Labels: enhancement :rocket:

#1050 refactor(avatar): function naming, and set feature in his own folder and files
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/features/user/userInformations.dto.ts
  yaki_backend/src/features/user_avatar/avatar.controller.ts
  yaki_backend/src/features/user_avatar/avatar.dto.ts
  yaki_backend/src/features/user_avatar/avatar.enum.ts
  yaki_backend/src/features/user_avatar/avatar.repository.ts
  yaki_backend/src/features/user_avatar/avatar.service.ts
  yaki_backend/src/router.ts
  yaki_backend/src/utils/PictureProcessing.ts
  yaki_backend/src/utils/statusCode.enum.ts
Labels: other

#1047 feat(App_bar_date): add conditionnal rendering
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/features/shared/app_bar_date.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
Labels: enhancement :rocket:

#1052 Fix/kisweb and password view
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/ui/password/change_password.dart
Labels: bug :bug:

#1053 feat(node_changePW): feat to change current password for a new one
  yaki_backend/src/errors/dataOrDataBaseError.ts
  yaki_backend/src/features/password/password.controller.ts
  yaki_backend/src/features/password/password.repository.ts
  yaki_backend/src/features/password/password.service.ts
  yaki_backend/src/features/user/user.controller.ts
  yaki_backend/src/features/user/user.repository.ts
  yaki_backend/src/features/user/user.service.ts
  yaki_backend/src/router.ts
Labels: enhancement :rocket:, backend-mobile

#1055 fix(avatar_response): fix improper response in case of default avatar choice
  yaki_backend/src/features/user_avatar/avatar.controller.ts
Labels: bug :bug:

#1057 fix(ScreenSize): fix size & add scrollController
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#1058 fix(ProfilAppBar): comment appbar wait for fix
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#1054 fix(fetch-password-profil): fetch password in page profile
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: bug :bug:

#1060 fix(RedirectionError): comment useless code
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
Labels: bug :bug:

#1064 fix(SplashScreen): Add duration
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
Labels: bug :bug:

#1056 fix(design-yaki): design in all pages with yaki ui
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/password/change_password.dart
  yaki_mobile/lib/presentation/features/password/forgot_password.dart
  yaki_mobile/lib/presentation/features/registration/form_functionality.dart
  yaki_mobile/lib/presentation/features/registration/registration.dart
  yaki_mobile/lib/presentation/features/registration/view/registration_snackbar.dart
Labels: bug :bug:

#1066 fix(email-support): support email
  yaki_mobile/lib/presentation/features/shared/feedback_user.dart
Labels: bug :bug:

#1072 fix(UpperCase): add uppercase in trad file
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart
Labels: bug :bug:

#1071 feat(LockRotateScreen): Lock portaitMode
  yaki_mobile/lib/main.dart
Labels: enhancement :rocket:

#1070 fix(TrimAuthenticate): add trim to login&password
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/registration/registration.dart
Labels: bug :bug:

#1073 Feat/cell card display avatar
  yaki_backend/src/__test__/teammate.test.ts
  yaki_backend/src/features/teammate/teammate.controller.ts
  yaki_backend/src/features/teammate/teammate.repository.ts
  yaki_backend/src/features/teammate/teammate.service.ts
  yaki_backend/src/features/teammate/userWithDeclarationAndAvatar.dtoOut.ts
  yaki_backend/src/features/user_avatar/avatar.controller.ts
  yaki_backend/src/features/user_avatar/avatar.dto.ts
  yaki_backend/src/features/user_avatar/avatar.repository.ts
  yaki_backend/src/features/user_avatar/avatar.service.ts
  yaki_backend/src/router.ts
  yaki_mobile/lib/app.dart
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/models/teammate_with_declaration_model.dart
  yaki_mobile/lib/data/models/teammate_with_declaration_model.g.dart
  yaki_mobile/lib/data/repositories/avatar_repository.dart
  yaki_mobile/lib/data/repositories/teammate_repository.dart
  yaki_mobile/lib/data/sources/remote/teammate_api.dart
  yaki_mobile/lib/data/sources/remote/teammate_api.g.dart
  yaki_mobile/lib/domain/entities/teammate_with_declaration_entity.dart
  yaki_mobile/lib/presentation/displaydata/avatar_enum.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/test/unit/data/models/teammate_model_test.dart
  yaki_mobile/test/unit/data/repositories/teammate_repository_test.dart
Labels: enhancement :rocket:, :iphone: mobile, backend-mobile

#1069 fix(fetch-error-widget-selection-teams): add icon profil in selection…
  yaki_mobile/lib/presentation/features/profile/profile.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Labels: bug :bug:

#1078 fix(redirection-page-change-password): redirection page change passwo…
  yaki_mobile/lib/presentation/features/password/change_password.dart
  yaki_mobile/lib/presentation/features/profile/profile.dart
Labels: bug :bug:

#1076 Feat/declaration timer
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Labels: enhancement :rocket:

#1080 fix(back): improper error handling cause nodeJs to crash
  yaki_backend/src/features/teammate/teammate.controller.ts
Labels: bug :bug:

#1081 test(JestTest): increase jest test
  yaki_backend/src/__test__/team-service.test.ts
  yaki_backend/src/__test__/teammate.test.ts
  yaki_backend/src/__test__/user-service.test.ts
  yaki_backend/src/features/user/user.service.ts
Labels: other

#1084 fix(back_halfday): correctly return the 2 objects for the halfday declaration
  yaki_backend/src/features/teammate/teammate.service.ts
Labels: bug :bug:

#1086 fix(button-feedback): configuration android manifest
  yaki_mobile/android/app/src/main/AndroidManifest.xml
  yaki_mobile/ios/Runner/Info.plist
  yaki_mobile/lib/presentation/features/shared/feedback_user.dart
  yaki_mobile/lib/presentation/styles/text_style.dart
Labels: bug :bug:

#1089 style(login_page): set BastiUI design for the login page
  yaki_admin/package-lock.json
  yaki_admin/package.json
  yaki_admin/public/favicon.png
  yaki_admin/src/assets/images/banner2.png
  yaki_admin/src/assets/images/eye.png
  yaki_admin/src/assets/images/eyes_closed.png
  yaki_admin/src/assets/images/eyes_visible.png
  yaki_admin/src/assets/images/splashscreen.svg
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/assets/style/_variables.scss
  yaki_admin/src/assets/style/main.css
  yaki_admin/src/assets/style/main.css.map
  yaki_admin/src/components/buttonPrimary.vue
  yaki_admin/src/components/buttonSecondary.vue
  yaki_admin/src/components/inputPassword.vue
  yaki_admin/src/components/inputText.vue
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/features/login/pages/PageLogin.vue
  yaki_admin/src/global-layouts/PageLayout.vue
  yaki_admin/src/main.ts
Labels: other

#1090 style(sidebar): set style and functionment for the sidebar
  yaki_admin/package-lock.json
  yaki_admin/src/assets/images/avatar_2.png
  yaki_admin/src/assets/images/briefcase-regular-24.png
  yaki_admin/src/assets/images/chevron-down-regular-24.png
  yaki_admin/src/assets/images/chevron-up-regular-24.png
  yaki_admin/src/assets/images/dots-vertical-rounded-regular-24.png
  yaki_admin/src/assets/images/group-regular-24.png
  yaki_admin/src/assets/images/hard-hat-regular-24.png
  yaki_admin/src/assets/images/pencil-regular-24.png
  yaki_admin/src/assets/images/plus_icon.png
  yaki_admin/src/assets/images/stats.png
  yaki_admin/src/assets/images/x_close.png
  yaki_admin/src/components/ButtonIcon.vue
  yaki_admin/src/components/ButtonPrimary.vue
  yaki_admin/src/components/ButtonSecondary.vue
  yaki_admin/src/components/ButtonTextIcon.vue
  yaki_admin/src/components/InputPassword.vue
  yaki_admin/src/components/InputText.vue
  yaki_admin/src/components/LoggedUserCard.vue
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/components/SideBarMenuDropDownElement.vue
  yaki_admin/src/components/SideBarMenuLink.vue
  yaki_admin/src/features/captain/CaptainPage.vue
  yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
  yaki_admin/src/features/captain/layouts/PageContentheader.vue
  yaki_admin/src/features/customer/components/SideBarCustomer.vue
  yaki_admin/src/features/login/components/LoginForm.vue
  yaki_admin/src/features/shared/components/HeaderMain.vue
  yaki_admin/src/features/shared/components/SideBarContent.vue
  yaki_admin/src/features/shared/components/SideBarTeamsListElement.vue
  yaki_admin/src/global-layouts/PageLayout.vue
  yaki_admin/src/global-layouts/SideBar.vue
Labels: other

#1091 style(team_header): set team header
  yaki_admin/package-lock.json
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/captain/layouts/PageContentheader.vue
  yaki_admin/src/features/shared/modal/services/modalState.ts
  yaki_admin/src/global-layouts/PageLayout.vue
Labels: other

#1092 style(user_list): set user list in team
  yaki_admin/package-lock.json
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/components/UserInfoCard.vue
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/captain/layouts/PageContentHeader.vue
  yaki_admin/src/features/shared/modal/component/ModalListDropDown.vue
  yaki_admin/src/global-layouts/PageContentLayout.vue
  yaki_admin/src/global-layouts/PageLayout.vue
Labels: other

#1131 fix(teamName_change): set ability back to edit the team name
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/features/modal/services/modalState.ts
  yaki_admin/src/models/team.type.ts
  yaki_admin/src/stores/teamStore.ts
Labels: bug :bug:

#1132 refactor(modal_logic): create pinia modal store and simplify logic
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/components/ModalDelete.vue
  yaki_admin/src/components/ModalTeamEditDelete.vue
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/components/UserInfoCard.vue
  yaki_admin/src/constants/modalMode.ts
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/captain/layouts/PageContentHeader.vue
  yaki_admin/src/features/captain/services/teamList.service.ts
  yaki_admin/src/features/modal/ModalFrame.vue
  yaki_admin/src/features/modal/services/modalState.ts
  yaki_admin/src/global-layouts/PageLayout.vue
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
Labels: other

#1138 fix(form_validation): using enter will validate login and create/edit modal
  yaki_admin/src/components/InputPassword.vue
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/features/login/components/LoginForm.vue
Labels: bug :bug:

#1139 fix(promises): use promise.all() to make sure to have all promises resolve at once
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/tsconfig.json
Labels: bug :bug:

#1140 fix(select_team): focus on the newly created team
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
Labels: bug :bug:

#1142 feat(info_no_team): change captain page content to display a no team message
  yaki_admin/src/assets/images/tuto_team_creation.png
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/components/ModalDelete.vue
  yaki_admin/src/components/PageContentNoTeam.vue
  yaki_admin/src/components/SideBarMenuDropDown.vue
  yaki_admin/src/constants/pathParam.ts
  yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
  yaki_admin/src/features/captain/layouts/PageContentHeader.vue
  yaki_admin/src/global-layouts/PageLayout.vue
  yaki_admin/src/models/team.type.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
Labels: enhancement :rocket:

#1143 fix(input_content): fix input field content for creation or edition
  yaki_admin/src/components/InputText.vue
  yaki_admin/src/components/InputTextArea.vue
  yaki_admin/src/components/ModalCreateEditTeam.vue
  yaki_admin/src/router/router.ts
  yaki_admin/src/stores/modalStore.ts
Labels: bug :bug:

#1144 fix(team_name): error message if user try to create a team without name
  yaki_admin/src/components/InputText.vue
  yaki_admin/src/components/ModalCreateEditTeam.vue
Labels: bug :bug:

#1134 feat(description): add description crud in team and tests junit
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamControllerTests.java
  yaki_backend/src/db/create_tables.sql
  yaki_karate/src/test/resources/adminTeam.feature
Labels: enhancement :rocket:

#1113 fix(splash_screen): change splash screen redirection process
  yaki_mobile/.vscode/launch.json
  yaki_mobile/ios/Podfile.lock
  yaki_mobile/ios/Runner.xcodeproj/project.pbxproj
  yaki_mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  yaki_mobile/ios/Runner/Info.plist
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/domain/entities/declaration_status.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/shared/app_bar_date.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/pubspec.lock
Labels: bug :bug:
