Repository XPEHO/YAKI, pull requests merged in 2024-06, with the labels that each got.

#1486 Feat/issue templates
  .github/ISSUE_TEMPLATE/archive/bug_report.md
  .github/ISSUE_TEMPLATE/archive/dor_issue_template.md
  .github/ISSUE_TEMPLATE/archive/feature_request.md
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/ui_element_template
Labels: enhancement :rocket:

#1489 fix(templates): Replaced milestones with prerequisites in ui
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/ui_element_template.md
Labels: bug :bug:

#1490 fix(statistics): altered team assignation to actually get teams
  yaki_admin/src/ui/views/StatisticsView.vue
Labels: bug :bug:

#1492 fix(invitation_page_env): Make unusable the pagination in a certain direction following the current page
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
Labels: bug :bug:

#1491 Fix(translations): moving language switch
  yaki_admin/src/ui/components/LanguageSwitch.vue
  yaki_admin/src/ui/components/PageContentHeader.vue
  yaki_admin/src/ui/views/LoginView.vue
  yaki_admin/src/ui/views/ProfileView.vue
  yaki_admin/src/ui/views/SideBarContent.vue
Labels: bug :bug:

#1457 fix(invitation_lists): Add query params in user endpoints to display only the user linked to the customer not already added in invitation lists
  yaki_admin/package-lock.json
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserResponseEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplUnitTest.java
Labels: bug :bug:

#1506 fix(template): base issue change
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: bug :bug:

#1512 feat(customer_team_list): Add the new teams view for customer with its navigation and translation associated
  yaki_admin/src/assets/translations/en.json
  yaki_admin/src/assets/translations/fr.json
  yaki_admin/src/router/router.ts
  yaki_admin/src/ui/views/SideBarContent.vue
  yaki_admin/src/ui/views/TeamListView.vue
  yaki_admin/test/captain/services/isActiveTeam.test.js
  yaki_admin/test/features/login.feature
  yaki_admin/test/features/team_management.feature
  yaki_admin/test/steps/detection.ts
  yaki_admin/test/steps/login.ts
  yaki_admin/test/steps/navigation.ts
  yaki_admin/test/steps/navigation_and_action.ts
  yaki_admin/test/steps/setup.ts
Labels: enhancement :rocket:

#1500 feat(statisticsdropdown): imported dropdown made necessary changes
  yaki_admin/src/assets/style/_variables.scss
  yaki_admin/src/main.ts
  yaki_admin/src/ui/layouts/PageContentLayout.vue
  yaki_admin/src/ui/views/StatisticsView.vue
  yaki_admin/src/utils/clickOutsideDirective.ts
Labels: enhancement :rocket:

#1511 fix(iOSNotifWhenDeclared): Add endpoint providing user's declared days
  yaki_backend/src/declaration.router.ts
  yaki_backend/src/features/declaration/declaration.controller.ts
  yaki_backend/src/features/declaration/declaration.repository.ts
  yaki_backend/src/features/declaration/declaration.service.ts
  yaki_mobile/ios/Podfile.lock
  yaki_mobile/ios/Runner/Info.plist
Labels: bug :bug:, javascript 🟨

#1515 feat(customer_team_list): Add team list on the teams view for the customer
  yaki_admin/src/assets/translations/en.json
  yaki_admin/src/assets/translations/fr.json
  yaki_admin/src/ui/components/TeamInfoCard.vue
  yaki_admin/src/ui/components/TeamList.vue
  yaki_admin/src/ui/views/TeamListView.vue
  yaki_admin/test/features/team_management.feature
  yaki_admin/test/steps/detection.ts
Labels: enhancement :rocket:

#1516 feat(statstable): added reworked table component from yaki ui
  yaki_admin/package-lock.json
  yaki_admin/src/models/dataTable.type.ts
  yaki_admin/src/ui/views/StatisticsView.vue
Labels: enhancement :rocket:

#1517 fix(lint_and_create_team_button): Fix error of the linter and height of create team button
  yaki_admin/package-lock.json
  yaki_admin/src/ui/components/TeamInfoCard.vue
  yaki_admin/src/ui/components/TeamList.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/views/TeamListView.vue
Labels: bug :bug:

#1523 fix(tests_cucumber_with_env): Add .env to be able to test with real users on UAT with cucumber
  yaki_admin/.env.example
  yaki_admin/package-lock.json
  yaki_admin/test/features/login.feature
  yaki_admin/test/features/team_management.feature
  yaki_admin/test/steps/login.ts
  yaki_admin/test/steps/setup.ts
Labels: bug :bug:

#1513 fix(flutterChanelForConditionalNotif): In flutter, retrieve declared days and pass them to the platform channels
  yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/MainActivity.kt
  yaki_mobile/ios/Runner/AppDelegate.swift
  yaki_mobile/ios/Runner/Constants.swift
  yaki_mobile/ios/Runner/MethodsChannel.swift
  yaki_mobile/lib/channels.dart
  yaki_mobile/lib/data/repositories/declaration_respository.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.dart
  yaki_mobile/lib/data/sources/remote/declaration_api.g.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
Labels: bug :bug:, dart :black_bird:

#1525 feat(teammanagementlastactivity): added new endpoint for testing
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/StatisticsServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/DeclarationJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/LastActivityEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/StatisticsService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/StatisticsController.java
Labels: enhancement :rocket:
