Repository XPEHO/YAKI, pull requests merged in 2024-01, with the labels that each got.

#1189 fix(expired_token): add validity token check on application opening
  yaki_backend/src/router.ts
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/data/repositories/token_repository.dart
  yaki_mobile/lib/data/sources/remote/token_api.dart
  yaki_mobile/lib/data/sources/remote/token_api.g.dart
  yaki_mobile/lib/presentation/state/notifiers/token_notifier.dart
  yaki_mobile/lib/presentation/state/providers/token_provider.dart
  yaki_mobile/pubspec.lock
Labels: bug :bug:

#1190 feat(credential_navigation): verify user credential to lock or unlock admin functionalities
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuLink.vue
  yaki_admin/src/ui/views/SideBarContent.vue
Labels: enhancement :rocket:

#1192 fix(admin_front): prevent first team of the list to always be selected at page change
  yaki_admin/src/ui/views/TeamManagementView.vue
Labels: bug :bug:

#1193 fix(mobile_router): redirection issue on logging
  yaki_mobile/lib/app_router.dart
Labels: bug :bug:

#1194 fix(rollback): go back to preview version du to routing issue
  yaki_mobile/lib/app_router.dart
Labels: bug :bug:

#1195 fix(token verification): check token validity
  yaki_mobile/lib/app_router.dart
Labels: bug :bug:

#1196 fix(rollback): rollback token verificatin
  yaki_mobile/lib/app_router.dart
Labels: bug :bug:

#1203 fix(fetch-captains): change requets in back for fetch captains
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
Labels: bug :bug:

#1207 fix(hide_functions): hide functions not aviable depending of the user crendetials
  yaki_admin/src/envPlaceholder.ts
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuLink.vue
  yaki_admin/src/ui/views/SideBarContent.vue
  yaki_admin/tsconfig.json
Labels: bug :bug:

#1206 refactor(invitation): review user invitation presentation and structure
  yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue
  yaki_admin/src/features/invitation/components/InvitationCard.vue
  yaki_admin/src/features/invitation/components/InvitationViewHeader.vue
  yaki_admin/src/features/invitation/components/UserInvitationCard.vue
  yaki_admin/src/features/invitation/components/UserInvitationList.vue
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/features/invitation/services/invitationService.ts
  yaki_admin/src/features/modal/services/modalState.ts
  yaki_admin/src/features/shared/components/DefaultButton.vue
  yaki_admin/src/features/shared/components/EditAndDeleteButtons.vue
  yaki_admin/src/features/shared/components/HeaderContentPage.vue
  yaki_admin/src/features/shared/components/SideBarButton.vue
  yaki_admin/src/features/shared/components/SideBarCategoryElement.vue
  yaki_admin/src/features/shared/components/UserCard.vue
  yaki_admin/src/ui/components/LoggedUserCard.vue
  yaki_admin/src/ui/components/PageContentHeader.vue
  yaki_admin/src/ui/components/modals/ModalDelete.vue
  yaki_admin/src/ui/views/CaptainsManagementView.vue
  yaki_admin/src/ui/views/TeamManagementView.vue
Labels: other

#1215 feat(team_logo): admin back create endpoint to save and get team logo
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamLogoModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamLogoRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamLogoEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamLogoService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/LocationServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoControllerTests.java
  yaki_backend/src/db/create_tables.sql
Labels: enhancement :rocket:

#1216 feat(team_logo): admin back create endpoint to save and get team logo (#1215)
  yaki_admin/src/composable/userFilePicker.ts
  yaki_admin/src/features/invitation/components/InvitationViewHeader.vue
  yaki_admin/src/models/TeamLogo.type.ts
  yaki_admin/src/services/teamLogo.service.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/ui/components/PageContentHeader.vue
  yaki_admin/src/ui/components/UserList.vue
  yaki_admin/src/ui/components/buttons/ButtonIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonTextIcon.vue
  yaki_admin/src/ui/components/buttons/ButtonTextSized.vue
  yaki_admin/src/ui/components/inputs/InputPassword.vue
  yaki_admin/src/ui/components/inputs/InputTextArea.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/utils/images.utils.ts
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java
Labels: enhancement :rocket:

#1218 feat(admin_logo): delete logo end point
  yaki_admin/src/services/teamLogo.service.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
Labels: enhancement :rocket:

#1219 feat(front): create logging loader and error message for error at logging
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/assets/style/main.css
  yaki_admin/src/assets/style/main.css.map
  yaki_admin/src/services/login.service.ts
  yaki_admin/src/stores/authStore.ts
  yaki_admin/src/ui/components/LoginForm.vue
  yaki_admin/src/ui/components/buttons/ButtonPrimary.vue
Labels: enhancement :rocket:

#1221 fix(logo_deletion): review modal deletion press behavior
  yaki_admin/src/composable/userFilePicker.ts
  yaki_admin/src/ui/components/buttons/ButtonPrimary.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
Labels: bug :bug:

#1175 fix(removed-captain-customer-page): fix fetch captains list in custom…
  yaki_admin/src/constants/modalMode.enum.ts
  yaki_admin/src/router/router.ts
  yaki_admin/src/services/captain.service.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/roleStore.ts
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/UserList.vue
  yaki_admin/src/ui/components/modals/ModalDelete.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CaptainModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/CaptainEntity.kt
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImplTest.java
Labels: bug :bug:

#1224 fix(admin_front): fix team deletion, fix image aspect ratio, fix new team default image
  yaki_admin/package-lock.json
  yaki_admin/src/features/invitation/components/InvitationViewHeader.vue
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/ui/components/PageContentHeader.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamLogoService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoController.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImplTest.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoControllerTests.java
Labels: bug :bug:

#1226 fix(removed-search-bar): removed search icon
  yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Labels: bug :bug:

#1237 fix(translate-mobile): fix error tranlate mobile
  yaki_mobile/assets/translations/en.json
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
Labels: bug :bug:

#1238 fix(design-admin-byxpeho-privacy): style for byxpepho and provacy to …
  yaki_admin/src/assets/style/_variables.scss
  yaki_admin/src/ui/views/LoginView.vue
Labels: bug :bug:

#1240 fix(flutter): user avatar not displaying, and summary declaration was skipping
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
Labels: bug :bug:

#1241 feat(mobile): splash screen redirection no futur delay, add token validity verification
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/state/notifiers/token_notifier.dart
  yaki_mobile/lib/presentation/state/providers/token_provider.dart
Labels: enhancement :rocket:, :iphone: mobile

#1242 feat(cercle-avatar-user): create componenent initial avatar
  yaki_admin/src/ui/components/InitialAvatar.vue
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/utils/images.utils.ts
Labels: enhancement :rocket:

#1243 feat(image-avatar-invitation): insert avatar initial in invitation card
  yaki_admin/src/features/invitation/components/UserInvitationCard.vue
Labels: enhancement :rocket:

#1246 feat(back_mobile): create get teams logo end point
  yaki_backend/src/__test__/team-repository.test.ts
  yaki_backend/src/__test__/team-service.test.ts
  yaki_backend/src/features/team/team.controller.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/team/team.service.ts
  yaki_backend/src/features/team/teamLogo.dto.ts
  yaki_backend/src/team.router.ts
Labels: enhancement :rocket:, backend-mobile

#1247 feat(absence_page): absence page design and functionment
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/app_router.dart
  yaki_mobile/lib/presentation/features/absence/absence.dart
  yaki_mobile/lib/presentation/features/absence/view/absence_header.dart
  yaki_mobile/lib/presentation/features/shared/app_bar_go_back.dart
  yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
  yaki_mobile/lib/presentation/ui/vacation/vacation_selection_dialog.dart
  yaki_mobile/lib/presentation/ui/vacation/views/date_picker_popup.dart
  yaki_mobile/pubspec.lock
  yaki_mobile/pubspec.yaml
Labels: enhancement :rocket:

#1252 fix(card-delete): add space between and after from :
  yaki_admin/src/ui/components/modals/ModalDelete.vue
Labels: bug :bug:

#1255 fix(fr_translation): fix incorrect error message translation in absence date page
  yaki_mobile/assets/translations/fr.json
Labels: bug :bug:

#1254 fix(font-initial-avatar): change font
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/ui/components/InitialAvatar.vue
Labels: bug :bug:

#1258 fix(remove-take-picture-pwa): remove take picture on pwa
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
Labels: bug :bug:

#1259 feat(mobile_team_logo): retrive team logo from backend and display them if exist
  yaki_backend/src/__test__/team-repository.test.ts
  yaki_backend/src/__test__/team-service.test.ts
  yaki_backend/src/features/team/team.controller.ts
  yaki_backend/src/features/team/team.repository.ts
  yaki_backend/src/features/team/team.service.ts
  yaki_backend/src/team.router.ts
  yaki_mobile/lib/data/models/team_logo_model.dart
  yaki_mobile/lib/data/models/team_logo_model.g.dart
  yaki_mobile/lib/data/repositories/team_logo_repository.dart
  yaki_mobile/lib/data/repositories/teammate_repository.dart
  yaki_mobile/lib/data/sources/remote/team_logo_api.dart
  yaki_mobile/lib/data/sources/remote/team_logo_api.g.dart
  yaki_mobile/lib/domain/entities/team_logo_entity.dart
  yaki_mobile/lib/domain/entities/teammate_with_declaration_entity.dart
  yaki_mobile/lib/presentation/displaydata/declaration_enum.dart
  yaki_mobile/lib/presentation/features/absence/absence.dart
  yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart
  yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
  yaki_mobile/lib/presentation/features/shared/team_logo_image.dart
  yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_collapsed_chips_row.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_opened_iconchips.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/collapsed_team_logo_chip.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
  yaki_mobile/lib/presentation/features/user_declaration_summary/view/summary_chips_duo.dart
  yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_logo_notifier.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_future_provider.dart
  yaki_mobile/lib/presentation/state/providers/team_logo_provider.dart
  yaki_mobile/lib/presentation/state/providers/teammate_future_provider.dart
  yaki_mobile/lib/presentation/state/state/team_page_state.dart
  yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
  yaki_mobile/test/unit/mocking.mocks.dart
Labels: enhancement :rocket:

#1262 feat(mobile_team): teams summary page add unavailable status for teams user is not into
  yaki_mobile/assets/images/unavailable.svg
  yaki_mobile/assets/images/unknown.svg
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_collapsed_chips_row.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_opened_iconchips.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/unavailable_icon_chip.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
  yaki_mobile/lib/presentation/state/providers/team_provider.dart
Labels: enhancement :rocket:

#1260 fix(fetch-user): add extension page with new route for to have every …
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Labels: bug :bug:

#1264 fix(get-total-pages): add the possibility to have the total page for …
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Labels: bug :bug:

#1266 fix(mobile_avatar): fix appearance of letter avatar, and fix team fetch when declared
  yaki_mobile/lib/presentation/features/authentication/authentication.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/teammates_category_list.dart
  yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart
Labels: bug :bug:

#1267 fix(mobile_time): correct time since declaration
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Labels: bug :bug:

#1269 fix(forgot_password): remove forgot button, replace by a text indicatif to reset the PW
  yaki_admin/src/ui/components/LoginForm.vue
Labels: bug :bug:

#1273 fix(team_fetch): correctly detect if the user is not part of the team anymore before fetch
  yaki_backend/src/features/team/team.repository.ts
Labels: bug :bug:

#1271 Fix/add request user
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
Labels: bug :bug:

#1274 fix(mobile_absence): do not display team chips along with an afternoonn absence in teams summary page
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_opened_iconchips.dart
Labels: bug :bug:

#1278 fix(profil_acess): add profil access in the page of user without teams
  yaki_mobile/lib/presentation/ui/default/user_default_redirection.dart
Labels: bug :bug:
