Repository XPEHO/YAKI, pull requests merged in 2024-02, with the labels that each got.

#1279 style(loader): fix loader position
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/ui/components/LoginForm.vue
Labels: other

#1281 style(loader): fix admin loader
  yaki_admin/src/assets/style/_style.scss
  yaki_admin/src/assets/style/main.css
  yaki_admin/src/assets/style/main.css.map
Labels: other

#1276 fix(backend-admin-create-customer): fix the creation of customer with…
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/CustomerModel.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
  yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImplTest.java
Labels: bug :bug:

#1291 fix(dependabots-flutter): add use super parameters
  yaki_mobile/analysis_options.yaml
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
  yaki_mobile/lib/presentation/features/shared/app_bar_date.dart
  yaki_mobile/lib/presentation/features/shared/feedback_user.dart
  yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
  yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
  yaki_mobile/lib/presentation/features/teams_declarations_summary/view/modal_filter.dart
  yaki_mobile/lib/presentation/ui/status/vacation_status.dart
Labels: bug :bug:

#1297 refactor(store): move team method from modalstore to teamstore, so for teammate and captain
  yaki_admin/src/composable/userFilePicker.ts
  yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
  yaki_admin/src/stores/authStore.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
  yaki_admin/src/ui/views/TeamManagementView.vue
  yaki_admin/src/utils/images.utils.ts
Labels: other

#1299 fix(front_admin): creating a team with a logo will not lead to team potential not have his logo
  yaki_admin/src/composable/userFilePicker.ts
  yaki_admin/src/stores/captainStore.ts
  yaki_admin/src/stores/selectedRole.ts
  yaki_admin/src/stores/teamLogoStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/stores/teammateStore.ts
  yaki_admin/src/ui/components/UserInfoCard.vue
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
Labels: bug :bug:

#1300 fix(admin_team_redirection): fix incorrect redirection after team creation while on the deleted team screen resume
  yaki_admin/src/router/router.ts
  yaki_admin/src/stores/teamLogoStore.ts
  yaki_admin/src/stores/teamStore.ts
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/views/ModalFrameView.vue
Labels: bug :bug:

#1301 fix(admin_team): selected team after creation to have value aviable to the logo creation
  yaki_admin/src/stores/teamLogoStore.ts
  yaki_admin/src/stores/teamStore.ts
Labels: bug :bug:

#1298 feat(display-user-sidebar-admin): create route in back
  yaki_admin/src/services/users.service.ts
  yaki_admin/src/ui/components/LoggedUserCard.vue
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Labels: enhancement :rocket:

#1302 fix(mobile_registration): set correct error message when email is already used. review snackbar message colors for readability
  yaki_mobile/assets/translations/en.json
  yaki_mobile/assets/translations/fr.json
  yaki_mobile/lib/presentation/features/registration/registration.dart
Labels: bug :bug:

#1304 fix(pic_upload): change upload picture button color button to be more visible
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
Labels: bug :bug:

#1308 fix(pic_preview): reset the preview when selecting a new picture
  yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
Labels: bug :bug:

#1312 fix(ci_version): fix flutter ci version
  .github/workflows/docker push release.yaml
  .github/workflows/docker push.yaml
  .github/workflows/test_&_build.yaml
  yaki_mobile/pubspec.lock
Labels: bug :bug:

#1314 chore(add-security-sonarqube-frontend-admin): add security with the r…
  yaki_admin/src/ui/components/LoginForm.vue
  yaki_admin/src/ui/views/LoginView.vue
Labels: chore :construction_worker_man:

#1316 chore(error-typescript-report-sonarqube): fix error typescript with t…
  yaki_admin/src/stores/modalStore.ts
  yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
  yaki_admin/src/ui/views/SideBarContent.vue
Labels: chore :construction_worker_man:

#1320 fix(bug-back-admin-sonarque): report bug in sonarqure recommand to Eq…
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamLogoEntity.java
  yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntityWithID.java
Labels: bug :bug:

#1322 fix(bug-front-admin-sonarqube): add sans serif for the font family an…
  yaki_admin/src/features/invitation/components/InvitationViewHeader.vue
  yaki_admin/src/features/invitation/components/UserInvitationList.vue
  yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue
  yaki_admin/src/ui/views/LoginView.vue
Labels: bug :bug:

#1327 fix(flutter_versin): updated CI docker push and release for flutter f…
  .github/workflows/docker push release.yaml
Labels: bug :bug:
